// @surface-orphan-ok — the basemap ObjectMap draws on; both are parked until
// the Object Explorer map view lands. See ObjectMap.tsx.
// Self-hosted MapLibre basemap. Serving the whole basemap — tiles, glyphs, and
// sprite — from our OWN domain means no ad-blocker, Brave Shields, CSP, or proxy
// can block it (that was the failure that kept the map black). Tiles are PMTiles
// files read via HTTP range requests; the dark style is generated by
// protomaps-themes-base. Both libs are dynamically imported so they only load
// when a basemap is actually configured.
//
// Two-tier coverage: a world file (planet extract, low zoom) renders everywhere;
// a detail file (small per-region extract, street-level) takes over above the
// world's max zoom. Onboarding a hotel in a new region = extract a new bbox.
//
// Configure via env, pointing at the Supabase public bucket (migration 195):
//   VITE_BASEMAP_PMTILES_URL        detail tiles, e.g. .../basemap/attica-z15.pmtiles
//   VITE_BASEMAP_MAXZOOM            detail data max zoom (camera cap), e.g. 15
//   VITE_BASEMAP_WORLD_PMTILES_URL  world tiles, e.g. .../basemap/planet.pmtiles
//   VITE_BASEMAP_WORLD_MAXZOOM      world data max zoom (handoff point), default 8
//   VITE_BASEMAP_GLYPHS_URL         .../basemap/fonts/{fontstack}/{range}.pbf
//   VITE_BASEMAP_SPRITE_URL         .../basemap/sprites/dark
// Unset → the map renders the tile-free SVG pin map (still never black).
// VITE_MAP_STYLE_URL is a separate escape hatch: a full external style URL.

import type { StyleSpecification, LayerSpecification } from 'maplibre-gl'

const env = import.meta.env as unknown as Record<string, string | undefined>
export const PMTILES_URL = env.VITE_BASEMAP_PMTILES_URL
const WORLD_URL    = env.VITE_BASEMAP_WORLD_PMTILES_URL
const WORLD_MAXZOOM = Number(env.VITE_BASEMAP_WORLD_MAXZOOM ?? 8)
const GLYPHS   = env.VITE_BASEMAP_GLYPHS_URL
const SPRITE   = env.VITE_BASEMAP_SPRITE_URL
const OVERRIDE = env.VITE_MAP_STYLE_URL

/** True when a real basemap is configured; otherwise the map runs SVG-only. */
export const MAP_TILES = !!PMTILES_URL || !!OVERRIDE

/** Deepest zoom with real data — the camera must not zoom past it or the map
 *  overzooms into a near-empty dark canvas that reads as "map didn't load". */
export const BASEMAP_MAX_ZOOM = PMTILES_URL
  ? Number(env.VITE_BASEMAP_MAXZOOM ?? 8)
  : 14

const pmtilesSource = (url: string) => ({
  type: 'vector' as const,
  url: `pmtiles://${url}`,
  attribution: '© <a href="https://openstreetmap.org/copyright">OpenStreetMap</a> · <a href="https://protomaps.com">Protomaps</a>',
})

type Zoomed = LayerSpecification & { minzoom?: number; maxzoom?: number }

/** The style maplibre should load: our self-hosted Protomaps dark basemap when a
 *  PMTiles URL is set, else an explicit VITE_MAP_STYLE_URL, else null (SVG mode). */
export async function buildMapStyle(): Promise<string | StyleSpecification | null> {
  if (!PMTILES_URL) return OVERRIDE ?? null
  const { layers, namedTheme } = await import('protomaps-themes-base')
  const theme = namedTheme('dark')
  const detail = layers('detail', theme, { lang: 'en' }) as Zoomed[]

  const style: StyleSpecification = {
    version: 8,
    glyphs: GLYPHS,
    sprite: SPRITE,
    sources: { detail: pmtilesSource(PMTILES_URL) },
    layers: detail,
  }

  if (WORLD_URL) {
    // World renders below the handoff zoom everywhere; detail takes over above
    // it (blank outside its bbox at deep zoom — you only zoom deep at hotels).
    style.sources.world = pmtilesSource(WORLD_URL)
    const world = (layers('world', theme, { lang: 'en' }) as Zoomed[]).map((l) => ({
      ...l, id: `w_${l.id}`, maxzoom: Math.min(l.maxzoom ?? WORLD_MAXZOOM, WORLD_MAXZOOM),
    }))
    const detailAbove = detail
      .filter((l) => (l.maxzoom ?? 24) > WORLD_MAXZOOM)
      .map((l) => ({ ...l, minzoom: Math.max(l.minzoom ?? 0, WORLD_MAXZOOM) }))
    style.layers = [...world, ...detailAbove]
  }

  return style
}
