// GENERATED by scripts/generate-ontology-types.mjs — do not edit.
// One interface per registered object type, from its properties in the
// ontology. Regenerate with `pnpm gen:ontology`; CI fails if it is stale.

/** Every registered object type, keyed by its api name. */
export interface OntologyTypes {
}

export type OntologyTypeName = keyof OntologyTypes
