// GENERATED by scripts/generate-ontology-types.mjs — do not edit.
// One interface per registered object type, from its properties in the
// ontology. Regenerate with `pnpm gen:ontology`; CI fails if it is stale.

/** Alert — A raised operational signal.
 *  Code-owned; records live in `notifications`. */
export interface Alert {
  message: string
  type: string
  timestamp: string
  read: boolean
  dismissed_reason?: string
}

/** Approved Answer — Curated Q&A served before any fresh LLM call.
 *  Code-owned; records live in `approved_answers`. */
export interface ApprovedAnswer {
  question: string
  answer: string
  embedding_ref?: string
  hit_count: number
  last_served_at?: string
  created_at: string
  retired_at?: string
}

/** Booking Forecast — Expected occupancy for a future date. Actuals land in occupancy_log; this is the forward curve.
 *  Code-owned; records live in `booking_forecasts`. */
export interface BookingForecast {
  date: string
  expected_occupancy_pct: number
  horizon_source: string
  created_by?: string
  created_at: string
  updated_at: string
}

/** Budget Allocation — Money allotted to a category for a period.
 *  Code-owned; records live in `budget_allocations`. */
export interface BudgetAllocation {
  period_month: string
  allocated_amount: number
  created_at: string
  updated_at: string
}

/** Case — A workflow envelope: trigger, proposals, outcome.
 *  Code-owned; records live in `cases`. */
export interface Case {
  title: string
  status: string
  resolved_at?: string
  created_at: string
}

/** Category — How products are grouped. Carries the FK every product classifies by.
 *  Code-owned; records live in `categories`. */
export interface Category {
  name: string
  order: number
  require_photo_for_removal_over?: number
  occupancy_sensitivity: number
}

/** Document Chunk — A passage of an ingested document, with its page.
 *  Code-owned; records live in `document_chunks`. */
export interface Chunk {
  chunk_key: string
  page: number
  text_preview: string
  text_full?: string
  created_at: string
  chunk_number: number
  summary?: string
}

/** Constraint — A rule evaluated at action submission.
 *  Code-owned; records live in `constraints`. */
export interface Constraint {
  body: string
  bucket: string
  severity: string
  active: boolean
  created_at: string
  deactivated_at?: string
}

/** Delivery — Stock arriving from a supplier.
 *  Code-owned; records live in `delivery_events`. */
export interface DeliveryEvent {
  ordered_qty: number
  received_qty: number
  expected_date: string
  actual_date?: string
  unit_cost_expected?: number
  unit_cost_actual?: number
  notes?: string
  created_at: string
}

/** Document — An ingested document with page-level provenance.
 *  Code-owned; records live in `documents`. */
export interface Document {
  title: string
  mime_type: string
  source: string
  ingestion_stage: string
  bucket_name: string
  storage_path: string
  size_bytes: number
  page_count?: number
  created_at: string
  updated_at: string
  sensitivity: string
}

/** Entity — A named thing discovered in a document.
 *  Code-owned; records live in `entities`. */
export interface Entity {
  name: string
  name_key?: string
  category: string
  created_at: string
}

/** Forecast Observation — A recorded forecast and what actually happened.
 *  Code-owned; records live in `forecast_observations`. */
export interface ForecastObservation {
  as_of: string
  horizon_days: number
  projected_units: number
  basis: string
  confidence: number
  sample_size: number
  source: string
  realized_units?: number
  signed_error?: number
  abs_pct_error?: number
  censored?: boolean
  scored_at?: string
  created_at: string
}

/** GL Account Mapping — How a movement maps onto a general-ledger account.
 *  Code-owned; records live in `gl_account_mappings`. */
export interface GlAccountMapping {
  mapping_type: string
  mapping_key: string
  gl_account_code: string
  gl_account_name: string
  created_at: string
  updated_at: string
}

/** Hotel — A property in the organization.
 *  Code-owned; records live in `hotels`. */
export interface Hotel {
  name: string
  address: string
  timezone: string
  currency: string
  created_at: string
  manager_approval_threshold: number
  director_approval_threshold: number
  escalation_timeout_hours: number
  auto_approve_threshold: number
  auto_po_enabled: boolean
  auto_invoice_tolerance_pct: number
}

/** Incident — A guest-reported incident.
 *  Operator-authored. */
export interface Incident {
  room: string
}

/** Zone — A location within a property.
 *  Code-owned; records live in `locations`. */
export interface Location {
  name: string
  created_at: string
}

/** Maintenance Request — A repair or upkeep task raised on the property.
 *  Operator-authored. */
export interface MaintenanceRequest {
  room: string
  urgent?: boolean
  reported_on?: string
  days_open?: number  // computed
}

/** Menu Item — A dish sold to a guest. Consumes variants through its recipe.
 *  Code-owned; records live in `menu_items`. */
export interface MenuItem {
  name: string
  category?: string
  sell_price?: number
  is_active: boolean
  created_at: string
}

/** Recipe Ingredient — A variant a menu item is made from.
 *  Code-owned; records live in `menu_item_ingredients`. */
export interface MenuItemIngredient {
  qty_per_serve: number
  unit?: string
  created_at: string
}

/** Occupancy Log — Recorded occupancy for a property on a date.
 *  Code-owned; records live in `occupancy_logs`. */
export interface OccupancyLog {
  date: string
  occupancy_pct: number
  occupied_rooms?: number
  total_rooms?: number
  source: string
  notes?: string
  created_at: string
}

/** Pick List — A set of items to be picked, assigned to somebody.
 *  Code-owned; records live in `pick_lists`. */
export interface PickList {
  name: string
  notes?: string
  status: string
  assigned_to?: string
  due_date?: string
  created_by: string
  completed_at?: string
  created_at: string
}

/** Pick List Item — A line on a pick list.
 *  Code-owned; records live in `pick_list_items`. */
export interface PickListItem {
  quantity_planned: number
  quantity_picked: number
  notes?: string
  picked_at?: string
  created_at: string
}

/** PO Discrepancy — A mismatch between what was ordered, received and invoiced.
 *  Code-owned; records live in `po_discrepancies`. */
export interface PoDiscrepancy {
  po_value: number
  received_value: number
  invoiced_value: number
  variance_pct: number
  tolerance_pct: number
  status: string
  reviewed_by?: string
  reviewed_at?: string
  review_notes?: string
  detected_at: string
  supplier_name?: string
}

/** PO Invoice — An invoice received against a purchase order.
 *  Code-owned; records live in `po_invoices`. */
export interface PoInvoice {
  invoice_number: string
  invoice_date: string
  invoice_amount: number
  po_amount: number
  discrepancy_amount: number
  status: string
  notes?: string
  submitted_by?: string
  approved_by?: string
  approved_at?: string
  created_at: string
}

/** POS Sale — A point-of-sale transaction that drew down stock.
 *  Code-owned; records live in `pos_sales`. */
export interface PosSale {
  quantity_sold: number
  sale_time: string
  source_system: string
  created_at: string
}

/** Principle — Operator feedback that shapes future proposals.
 *  Code-owned; records live in `principles`. */
export interface Principle {
  body: string
  category: string
  active: boolean
  created_at: string
  deactivated_at?: string
}

/** Product — A stocked product.
 *  Code-owned; records live in `products`. */
export interface Product {
  name: string
  description?: string
  sku: string
  image_url?: string
  cost: number
  enabled: boolean
  created_at: string
  updated_at: string
  shelf_life_days?: number
}

/** Product Batch — A batch of stock with its own expiry.
 *  Code-owned; records live in `product_batches`. */
export interface ProductBatch {
  lot_number?: string
  expiry_date?: string
  quantity: number
  received_at: string
  notes?: string
  status: string
}

/** Proposal — A typed action an agent proposed.
 *  Code-owned; records live in `proposals`. */
export interface Proposal {
  agent_name: string
  agent_version: string
  action_type: string
  confidence: number
  reasoning: string
  status: string
  refinement_note?: string
  decided_at?: string
  resulting_node_type?: string
  created_at: string
  edited_before_approval: boolean
}

/** Purchase Order — An order placed with a supplier.
 *  Code-owned; records live in `purchase_orders`. */
export interface PurchaseOrder {
  po_number: string
  supplier_name: string
  status: string
  notes?: string
  total_amount: number
  expected_delivery_date?: string
  sent_at?: string
  confirmed_at?: string
  closed_at?: string
  created_by?: string
  created_at: string
  updated_at: string
}

/** PO Line — One line on a purchase order: a variant, a quantity, a cost.
 *  Code-owned; records live in `purchase_order_lines`. */
export interface PurchaseOrderLine {
  ordered_qty: number
  received_qty: number
  unit_cost: number
  line_total: number
  notes?: string
}

/** Restock Receipt — Stock received against a restock request.
 *  Code-owned; records live in `restock_receives`. */
export interface RestockReceive {
  received_by?: string
  quantity_received: number
  lot_number?: string
  notes?: string
  received_at: string
  unit_cost?: number
}

/** Restock Request — A request to replenish a variant.
 *  Code-owned; records live in `restock_requests`. */
export interface RestockRequest {
  quantity_needed: number
  supplier?: string
  status: string
  date: string
  notes?: string
  is_auto_proposed: boolean
  estimated_cost?: number
  required_approval_tier: string
  approved_by?: string
  approved_at?: string
  approval_notes?: string
  rejected_by?: string
  rejected_at?: string
  rejected_reason?: string
  escalation_count: number
  last_escalated_at?: string
  created_at: string
  updated_at: string
}

/** Room — A guest room on the property.
 *  Operator-authored. */
export interface Room {
  floor?: number
}

/** Shift Handover — What one shift told the next.
 *  Code-owned; records live in `shift_handovers`. */
export interface ShiftHandover {
  created_by?: string
  window_hours: number
  started_at: string
  notes?: string
  created_at: string
}

/** Stock Log — An immutable record of a stock movement.
 *  Code-owned; records live in `stock_logs`. */
export interface StockLog {
  quantity_change: number
  balance_after: number
  reason: string
  timestamp: string
  is_revert: boolean
  revert_of?: string
  was_offline: boolean
  photo_url?: string
  category?: string
  source?: string
}

/** Stock Transfer — A lateral move of stock between properties.
 *  Code-owned; records live in `stock_transfers`. */
export interface StockTransfer {
  quantity: number
  reason: string
  status: string
  approved_at?: string
  created_at: string
}

/** Stocktake Line — One counted variant in a session, with its variance.
 *  Code-owned; records live in `stocktake_lines`. */
export interface StocktakeLine {
  system_qty: number
  counted_qty?: number
}

/** Stocktake Session — A counting round: what was counted, by whom, when.
 *  Code-owned; records live in `stocktake_sessions`. */
export interface StocktakeSession {
  created_by?: string
  status: string
  note?: string
  started_at: string
  committed_at?: string
}

/** Supplier — A vendor the organization orders from.
 *  Code-owned; records live in `suppliers`. */
export interface Supplier {
  name: string
  contact_name?: string
  email?: string
  phone?: string
  notes?: string
  created_at: string
  lead_time_days?: number
  lead_time_stddev?: number
  lead_time_computed_at?: string
  lead_time_source: string
  on_time_pct?: number
  cost_variance_pct?: number
  reliability_sample_size: number
  reliability_computed_at?: string
}

/** Supplier Contract — An agreed price and minimum order for one variant from one supplier, valid between two dates.
 *  Code-owned; records live in `supplier_contracts`. */
export interface SupplierContract {
  supplier_name: string
  contracted_price: number
  min_order_qty?: number
  contract_start: string
  contract_end?: string
  notes?: string
  is_active: boolean
  created_at: string
  updated_at: string
}

/** User — A person acting in the organization.
 *  Code-owned; records live in `profiles`. */
export interface User {
  email: string
  role: string
  created_at: string
}

/** Variant — A specific variant of a product — the unit inventory is counted in.
 *  Code-owned; records live in `variant_ontology`. */
export interface Variant {
  name?: string
  sku?: string
  current_stock?: number
  expiry_date?: string
  lot_number?: string
  serial?: string
  cost?: number
  low_stock_threshold?: number
  enabled?: boolean
  barcode?: string
  reminder_date?: string
  reminder_label?: string
  unit_of_measure?: string
  status?: string
  active?: boolean
  has_stock_history?: boolean
  par_source?: string
  projected_demand?: number
  forecast_basis?: string
  forecast_confidence?: number
  forecast_horizon_days?: number
  forecast_as_of?: string
}

/** Every registered object type, keyed by its api name. */
export interface OntologyTypes {
  alert: Alert
  approved_answer: ApprovedAnswer
  booking_forecast: BookingForecast
  budget_allocation: BudgetAllocation
  case: Case
  category: Category
  chunk: Chunk
  constraint: Constraint
  delivery_event: DeliveryEvent
  document: Document
  entity: Entity
  forecast_observation: ForecastObservation
  gl_account_mapping: GlAccountMapping
  hotel: Hotel
  incident: Incident
  location: Location
  maintenance_request: MaintenanceRequest
  menu_item: MenuItem
  menu_item_ingredient: MenuItemIngredient
  occupancy_log: OccupancyLog
  pick_list: PickList
  pick_list_item: PickListItem
  po_discrepancy: PoDiscrepancy
  po_invoice: PoInvoice
  pos_sale: PosSale
  principle: Principle
  product: Product
  product_batch: ProductBatch
  proposal: Proposal
  purchase_order: PurchaseOrder
  purchase_order_line: PurchaseOrderLine
  restock_receive: RestockReceive
  restock_request: RestockRequest
  room: Room
  shift_handover: ShiftHandover
  stock_log: StockLog
  stock_transfer: StockTransfer
  stocktake_line: StocktakeLine
  stocktake_session: StocktakeSession
  supplier: Supplier
  supplier_contract: SupplierContract
  user: User
  variant: Variant
}

export type OntologyTypeName = keyof OntologyTypes
