// GENERATED by scripts/generate-client.mjs — do not edit.
//
// Every platform entity the app role may execute, as a typed value. Import
// the entity, not its name: `client(datasetView).executeFunction({…})`.
// Regenerate with `pnpm gen:client`; CI fails if it is stale.

import type { ActionType, FunctionType, Json } from './client'

// NOT GENERATED — overloaded, and an entity has one API name:
//   public.rid_of

// ── ACTION TYPES (3) ────────────────────────────────────────────────
// Volatile: they may write. Applied, not executed.

/**
 *  Create the dataset's real table in the datasets schema from the schema on
 *  a transaction. SECURITY DEFINER because it issues DDL; it checks
 *  can_write_dataset first.
 */
export const datasetMaterialize = { apiName: 'dataset_materialize', kind: 'action' } as ActionType<
  { p_dataset: string; p_transaction: string },
  string
>

/**
 *  Every RLS-guarded table that the role PostgREST connects as cannot read.
 *  Derived from pg_class, never enumerated. Found the recursion in migration
 *  403 that no other guard could see.
 */
export const rlsViolations = { apiName: 'rls_violations', kind: 'action' } as ActionType<
  Record<string, never>,
  { relation: string; problem: string }[]
>

/**
 *  One save for an object type and its properties, into a named ontology.
 *  Invoker rights: the RLS policies decide.
 */
export const saveObjectType = { apiName: 'save_object_type', kind: 'action' } as ActionType<
  { p_object_type: Json; p_properties: Json },
  string
>

// ── FUNCTIONS (51) ───────────────────────────────────────────────────
// Stable or immutable: they read and return.

/**
 *  Every property this action type can write. "Because we have only defined
 *  one action that touches only the Root Cause property, this is the only
 *  property that users can edit."
 */
export const actionEditableProperties = { apiName: 'action_editable_properties', kind: 'function' } as FunctionType<
  { p_action: string },
  { object_type: string; property: string; rule_kind: string }[]
>

export const actionRuleKinds = { apiName: 'action_rule_kinds', kind: 'function' } as FunctionType<
  Record<string, never>,
  { kind: string; targets: string; note: string }[]
>

export const activeScopedSession = { apiName: 'active_scoped_session', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

/**
 *  Current user's organization scope. Mirrors auth_hotel_id(). JWT claim
 *  takes precedence; falls back to parent org of hotel.
 */
export const authOrgId = { apiName: 'auth_org_id', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

export const authRole = { apiName: 'auth_role', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

export const canApplyMarking = { apiName: 'can_apply_marking', kind: 'function' } as FunctionType<
  { p_marking: string },
  boolean
>

export const canChooseScopedSession = { apiName: 'can_choose_scoped_session', kind: 'function' } as FunctionType<
  { p_session: string },
  boolean
>

export const canManageMarking = { apiName: 'can_manage_marking', kind: 'function' } as FunctionType<
  { p_marking: string },
  boolean
>

export const canReadActionType = { apiName: 'can_read_action_type', kind: 'function' } as FunctionType<
  { p_action: string },
  boolean
>

/**
 *  FILE access: same organization, and a member of every file marking. Gates
 *  the registry row, the schema and the transaction history — not the rows.
 */
export const canReadDataset = { apiName: 'can_read_dataset', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

/**
 *  DATA access: file access plus every data marking propagated from upstream.
 *  Gates rows only.
 */
export const canReadDatasetData = { apiName: 'can_read_dataset_data', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

export const canRemoveMarking = { apiName: 'can_remove_marking', kind: 'function' } as FunctionType<
  { p_marking: string },
  boolean
>

export const canSeeMarkingCategory = { apiName: 'can_see_marking_category', kind: 'function' } as FunctionType<
  { p_category: string },
  boolean
>

export const canWriteActionType = { apiName: 'can_write_action_type', kind: 'function' } as FunctionType<
  { p_action: string },
  boolean
>

/**
 *  Same organization, an editor role, AND membership of every file marking.
 *  The marking term is not redundant with can_read_dataset: a role can never
 *  override a mandatory control, so it is stated on both sides.
 */
export const canWriteDataset = { apiName: 'can_write_dataset', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

export const canWriteDatasetData = { apiName: 'can_write_dataset_data', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

/**
 *  The slot-based Capabilities vocabulary, from metadata-typeclasses (the
 *  page it replaces) and the Geospatial panel screenshot. Time series is the
 *  other panel shape and lives in time_series_properties.
 */
export const capabilitySlots = { apiName: 'capability_slots', kind: 'function' } as FunctionType<
  Record<string, never>,
  { capability: string; slot: string; accepts: string[]; note: string }[]
>

/**
 *  The schema in force on a branch: the nearest one down the commit chain
 *  from its head. Per branch, because a datasource is a dataset ON A BRANCH.
 */
export const datasetBranchSchema = { apiName: 'dataset_branch_schema', kind: 'function' } as FunctionType<
  { p_branch: string },
  Json
>

export const datasetFieldSqlType = { apiName: 'dataset_field_sql_type', kind: 'function' } as FunctionType<
  { f: Json },
  string
>

export const datasetFieldValid = { apiName: 'dataset_field_valid', kind: 'function' } as FunctionType<
  { f: Json },
  boolean
>

export const datasetHistory = { apiName: 'dataset_history', kind: 'function' } as FunctionType<
  { p_branch: string; p_at?: string },
  { transaction_id: string; txn_type: string; committed_at: string; seq: number }[]
>

export const datasetHistoryFrom = { apiName: 'dataset_history_from', kind: 'function' } as FunctionType<
  { p_transaction: string; p_at?: string },
  { transaction_id: string; txn_type: string; committed_at: string; seq: number }[]
>

/**
 *  Every marking a dataset demands, tagged with which card it belongs in
 *  (file/data) and how it got there. Reads the same predicates the RLS
 *  policies do, so the panel cannot drift from the gate.
 */
export const datasetMarkings = { apiName: 'dataset_markings', kind: 'function' } as FunctionType<
  { p_dataset: string },
  { marking_id: string; name: string; color: string; category: string; kind: string; origin: string; satisfied: boolean }[]
>

/**
 *  A tabular dataset schema: an array of uniquely-named fields whose types
 *  are the fifteen from data-integration/datasets, with the four
 *  parameterised ones carrying their parameters.
 */
export const datasetSchemaValid = { apiName: 'dataset_schema_valid', kind: 'function' } as FunctionType<
  { fields: Json },
  boolean
>

/**
 *  The current view of a branch, or the view at a point in time. For "as of
 *  transaction X" use dataset_view_from, which cannot be truncated.
 */
export const datasetView = { apiName: 'dataset_view', kind: 'function' } as FunctionType<
  { p_branch: string; p_at?: string },
  { file_id: string; logical_path: string; row_count: number }[]
>

/**
 *  The view as of a transaction — the precision-safe anchor. Prefer this over
 *  a client-supplied timestamp: a JS Date truncates timestamptz to
 *  milliseconds and drops the transaction it names.
 */
export const datasetViewFrom = { apiName: 'dataset_view_from', kind: 'function' } as FunctionType<
  { p_transaction: string; p_at?: string },
  { file_id: string; logical_path: string; row_count: number }[]
>

export const datasetViewTransactions = { apiName: 'dataset_view_transactions', kind: 'function' } as FunctionType<
  { p_branch: string; p_at?: string },
  { transaction_id: string; txn_type: string; seq: number }[]
>

export const datasetViewTransactionsFrom = { apiName: 'dataset_view_transactions_from', kind: 'function' } as FunctionType<
  { p_transaction: string; p_at?: string },
  { transaction_id: string; txn_type: string; seq: number }[]
>

/**
 *  The caller organization's ontology when it has exactly one. Raises rather
 *  than guessing when there are none or several — the Ontology Manager picker
 *  is a choice, and a silent wrong guess writes to the wrong ontology.
 */
export const defaultOntology = { apiName: 'default_ontology', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

/**
 *  The file markings of every transitive input, arriving here as data
 *  markings. A union over inputs: one marked input marks everything
 *  downstream.
 */
export const effectiveDataMarkings = { apiName: 'effective_data_markings', kind: 'function' } as FunctionType<
  { p_dataset: string },
  string[]
>

/**
 *  Which markings a resource demands by the file route. SECURITY DEFINER
 *  because it reads `datasets` to resolve project inheritance, and is itself
 *  called from the datasets policy — invoker rights recurse.
 */
export const effectiveFileMarkings = { apiName: 'effective_file_markings', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string },
  string[]
>

/**
 *  direct = applied on this resource; file_hierarchy = inherited from its
 *  project. Foundry renders the second with a folder sidecar icon on the
 *  chip.
 */
export const fileMarkingOrigin = { apiName: 'file_marking_origin', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string; p_marking: string },
  string
>

export const hasResourceRole = { apiName: 'has_resource_role', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string; p_min: string },
  boolean
>

/**
 *  The generated accessor for one end of a link type: .get() where that side
 *  sees one, .all() where it sees many. Derived from cardinality so the two
 *  can never disagree.
 */
export const linkAccessor = { apiName: 'link_accessor', kind: 'function' } as FunctionType<
  { p_link: string; p_side: string },
  string
>

/**
 *  Grammar for object_sets.traversals — every element is {edgeType,
 *  direction: forward|reverse, filters?}, at most 3 hops (Foundry caps Search
 *  Around depth at 3).
 */
export const objectSetTraversalsValid = { apiName: 'object_set_traversals_valid', kind: 'function' } as FunctionType<
  { p: Json },
  boolean
>

/**
 *  Every reason an object type cannot be saved, from the two lists in
 *  create-object-type#mandatory-object-type-fields. This is what the "4
 *  errors" badge counts.
 */
export const objectTypeProblems = { apiName: 'object_type_problems', kind: 'function' } as FunctionType<
  { p_object_type: string },
  { scope: string; subject: string; problem: string }[]
>

/**
 *  Every well-formedness violation in the ontology, as rows. The linting half
 *  of what check:platform was doing by assertion — see
 *  superrepo/core-concepts "Ontology linting".
 */
export const ontologyViolations = { apiName: 'ontology_violations', kind: 'function' } as FunctionType<
  Record<string, never>,
  { object_type: string; scope: string; subject: string; problem: string }[]
>

/**
 *  Disjunctive: passes when there is no session, when the resource has no
 *  markings, or when the resource carries at least one of the session's
 *  markings. Stacks on top of the conjunctive satisfies_markings — it does
 *  not replace it.
 */
export const passesScopedSession = { apiName: 'passes_scoped_session', kind: 'function' } as FunctionType<
  { p_markings: string[] },
  boolean
>

export const primaryKeyAdvice = { apiName: 'primary_key_advice', kind: 'function' } as FunctionType<
  { p_base_type: string },
  string
>

/**
 *  yes | discouraged | no, from properties-overview. Only `no` is a
 *  constraint; `discouraged` is a warning carrying primary_key_advice().
 */
export const primaryKeyEligibility = { apiName: 'primary_key_eligibility', kind: 'function' } as FunctionType<
  { p_base_type: string },
  string
>

/**
 *  The caller's role on a project: the stronger of their explicit grant and
 *  the project's organization-wide default role.
 */
export const projectRole = { apiName: 'project_role', kind: 'function' } as FunctionType<
  { p_project: string },
  string
>

export const propertyBaseTypes = { apiName: 'property_base_types', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

export const reservedApiNames = { apiName: 'reserved_api_names', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

/**
 *  The single definition of file access: same organization, a member of every
 *  file marking, and inside the scoped session. Every policy and helper
 *  composes this rather than restating it — restating it is what produced
 *  migrations 395 and 403.
 */
export const resourceFileAccess = { apiName: 'resource_file_access', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string; p_org: string },
  boolean
>

/**
 *  A resource's filepath: /<space path>/<project>/<name>. Falls back to
 *  /<project>/<name> while a project has no space, which is the pre-397
 *  shape.
 */
export const resourceLocation = { apiName: 'resource_location', kind: 'function' } as FunctionType<
  { p_project: string; p_name: string },
  string
>

/**
 *  The <locator> of a RID: everything after the fourth separator, because the
 *  locator may itself contain dots (palantir/resource-identifier). NULL when
 *  malformed or not a uuid.
 */
export const ridLocator = { apiName: 'rid_locator', kind: 'function' } as FunctionType<
  { p_rid: string },
  string
>

export const roleRank = { apiName: 'role_rank', kind: 'function' } as FunctionType<
  { p_role: string },
  number
>

/**
 *  Conjunctive: "a user must be a member of ALL the Markings on a file,
 *  folder, or Project". Empty set passes — no markings is not a restriction.
 */
export const satisfiesMarkings = { apiName: 'satisfies_markings', kind: 'function' } as FunctionType<
  { p_markings: string[] },
  boolean
>

export const selectableScopedSessions = { apiName: 'selectable_scoped_sessions', kind: 'function' } as FunctionType<
  Record<string, never>,
  { id: string; name: string; description: string; markings: string[] }[]
>

export const titleKeyEligible = { apiName: 'title_key_eligible', kind: 'function' } as FunctionType<
  { p_base_type: string },
  boolean
>

/**
 *  Grammar for user_tools.parameters — every element is {key: lower_snake,
 *  type: text|number|boolean|date, required: bool}.
 */
export const userToolParamsValid = { apiName: 'user_tool_params_valid', kind: 'function' } as FunctionType<
  { p: Json },
  boolean
>

