// GENERATED by scripts/generate-client.mjs — do not edit.
//
// Every platform entity the app role may execute, as a typed value. Import
// the entity, not its name: `client(datasetView).executeFunction({…})`.
// Regenerate with `pnpm gen:client`; CI fails if it is stale.

import type { ActionType, FunctionType, Json } from './client'

// NOT GENERATED — overloaded, and an entity has one API name:
//   public.rid_of

// ── ACTION TYPES (39) ────────────────────────────────────────────────
// Volatile: they may write. Applied, not executed.

/**
 *  Apply an action: validate required parameters, run create/modify/delete
 *  rules in order, append to the edit log with the action recorded on each
 *  edit. The next index build merges the result. Criteria evaluation and the
 *  other four rule kinds refuse by name rather than half-working. Invoker —
 *  the edit lands through object_edits' own policy.
 */
export const applyAction = { apiName: 'apply_action', kind: 'action' } as ActionType<
  { p_action_type: string; p_parameters?: Json; p_primary_key?: string },
  number
>

/**
 *  Write an action type and its three components. Called by
 *  save_working_state and nothing else. Children are replaced wholesale —
 *  nothing outside the action references them by id — with natural keys
 *  (parameter api_name, criteria client keys) mapped to fresh uuids on land.
 */
export const applyActionType = { apiName: 'apply_action_type', kind: 'action' } as ActionType<
  { p_action: Json; p_parameters?: Json; p_rules?: Json; p_criteria?: Json },
  string
>

/**
 *  Writes the edit batch an Ontology edit function returned, in one
 *  transaction: the published ObjectEdit variants become object_edits
 *  instructions, an edit outside the version's provenance fails the action,
 *  and link edits are refused by name.
 */
export const applyFunctionEdits = { apiName: 'apply_function_edits', kind: 'action' } as ActionType<
  { p_action_type: string; p_edits: Json },
  number
>

/**
 *  Write an interface and its three clauses plus extensions. Called by
 *  save_working_state and nothing else. Properties and constraints upsert by
 *  natural key because implementations reference them by id; extensions
 *  replace as a set through the guards.
 */
export const applyInterface = { apiName: 'apply_interface', kind: 'action' } as ActionType<
  { p_interface: Json; p_properties?: Json; p_link_constraints?: Json; p_action_constraints?: Json; p_extends?: Json },
  string
>

/**
 *  Write an object type and its properties to the ontology. Called by
 *  save_working_state and by nothing else — a surface that calls this
 *  directly has skipped the session.
 */
export const applyObjectType = { apiName: 'apply_object_type', kind: 'action' } as ActionType<
  { p_object_type: Json; p_properties: Json; p_datasources?: Json },
  string
>

/**
 *  The arm dispatch save_working_state has always run, extracted once: a main
 *  save applies the caller's entries, a branch compose applies the overlay
 *  plus the composer's entries, a merge applies the overlay. Callers own
 *  validation, version bumps and cleanup.
 */
export const applyOneChange = { apiName: 'apply_one_change', kind: 'action' } as ActionType<
  { p_kind: string; p_id: string; p_op: string; p_fields: Json; p_ont: string },
  void
>

/**
 *  Write the latest indexed state of the object type into the output dataset:
 *  one SNAPSHOT transaction, schema from the properties' API names plus
 *  __is_deleted, prior transactions deleted because only the latest snapshot
 *  is guaranteed. Called by the surface; the automatic/periodic propagation
 *  modes are stored configuration, not a timer.
 */
export const buildMaterialization = { apiName: 'build_materialization', kind: 'action' } as ActionType<
  { p_materialization: string },
  number
>

/**
 *  Opens a proposal and snapshots one task per resource the branch changed.
 */
export const createProposal = { apiName: 'create_proposal', kind: 'action' } as ActionType<
  { p_branch: string; p_name: string; p_description?: string },
  string
>

/**
 *  Create a space and attach the caller's organization to it, in one call.
 *  Two separate writes cannot work: `insert into spaces … returning id` is
 *  REFUSED outright, because Postgres applies the SELECT policy to a
 *  RETURNING clause and that policy reads through space_organizations — a row
 *  that does not exist until the space does.
 */
export const createSpace = { apiName: 'create_space', kind: 'action' } as ActionType<
  { p_name: string; p_description?: string },
  string
>

/**
 *  Create the dataset's real table in the datasets schema from the schema on
 *  a transaction. SECURITY DEFINER because it issues DDL; it checks
 *  can_write_dataset first.
 */
export const datasetMaterialize = { apiName: 'dataset_materialize', kind: 'action' } as ActionType<
  { p_dataset: string; p_transaction: string },
  string
>

export const datasetRematerialize = { apiName: 'dataset_rematerialize', kind: 'action' } as ActionType<
  { p_dataset: string; p_transaction: string },
  string
>

/**
 *  Stage a deletion. The review dialog shows a deleted resource as an entry
 *  with a Deleted pill, so it is reviewable and discardable like any other
 *  change, and the row survives until save.
 */
export const deleteOntologyResource = { apiName: 'delete_ontology_resource', kind: 'action' } as ActionType<
  { p_kind: string; p_id: string },
  string
>

/**
 *  Discard one entry, or all of them. Per entry and not per field, because
 *  that is the only granularity the Review edits dialog offers.
 */
export const discardWorkingState = { apiName: 'discard_working_state', kind: 'action' } as ActionType<
  { p_kind?: string; p_id?: string; p_branch?: string },
  number
>

/**
 *  Insert an implementation and its per-property resolutions in one
 *  transaction, so 450's commit-time conformance judges the whole claim
 *  instead of refusing a bare row. Mappings name interface properties by
 *  natural key.
 */
export const implementInterface = { apiName: 'implement_interface', kind: 'action' } as ActionType<
  { p_object_type: string; p_interface: string; p_mappings?: Json },
  string
>

export const indexJobSpec = { apiName: 'index_job_spec', kind: 'action' } as ActionType<
  { p_type: string },
  string
>

export const indexObjectType = { apiName: 'index_object_type', kind: 'action' } as ActionType<
  { p_object_type: string; p_job: string },
  unknown
>

/**
 *  One lineage graph over datasets and object types: dataset inputs,
 *  datasource bindings, materializations as flow edges, link types as
 *  relations. Depth-limited each way, capped at 300 nodes with a truncated
 *  flag, visibility enforced per node with the caller's claims.
 */
export const lineageGraph = { apiName: 'lineage_graph', kind: 'action' } as ActionType<
  { p_kind: string; p_id: string; p_up?: number; p_down?: number },
  Json
>

/**
 *  Merges a proposal: blockers, then the branch's overlay through the same
 *  arms a main save uses, then the violations delta — atomically, in one
 *  transaction. Deliberately does NOT check who is merging beyond visibility:
 *  "merging only applies pre-authored and approved changes."
 */
export const mergeProposal = { apiName: 'merge_proposal', kind: 'action' } as ActionType<
  { p_proposal: string },
  void
>

/**
 *  "Only a constraint change mints one." The new constraint set lands as a
 *  fresh version in one call, so a version can never be half-written; earlier
 *  versions stay readable for consumers that pin (function repositories do;
 *  the ontology does not).
 */
export const mintValueTypeVersion = { apiName: 'mint_value_type_version', kind: 'action' } as ActionType<
  { p_value_type: string; p_constraints?: Json },
  number
>

export const objectDatasetJobSpec = { apiName: 'object_dataset_job_spec', kind: 'action' } as ActionType<
  { p_object_dataset: string },
  string
>

/**
 *  Finish rebase and save: apply the per-resource choices (Use Main deletes
 *  the branch row; Keep current refreshes its baseline to main's present),
 *  drop rows whose main resource is gone, stamp last_rebased_at. Auto-resolve
 *  is free in a field-level overlay — untouched fields never collide.
 */
export const rebaseBranch = { apiName: 'rebase_branch', kind: 'action' } as ActionType<
  { p_branch: string; p_resolutions?: Json },
  number
>

/**
 *  Every RLS-guarded table that the role PostgREST connects as cannot read.
 *  Derived from pg_class, never enumerated. Found the recursion in migration
 *  403 that no other guard could see.
 */
export const rlsViolations = { apiName: 'rls_violations', kind: 'action' } as ActionType<
  Record<string, never>,
  { relation: string; problem: string }[]
>

/**
 *  Re-attempts automation effects whose retry has come due, advancing the
 *  ladder until the published budget is spent — at which point the run fails
 *  and its fallback is released.
 */
export const runAutomationRetries = { apiName: 'run_automation_retries', kind: 'action' } as ActionType<
  { p_at?: string },
  number
>

/**
 *  One build: resolve the job set (manual or upstream), refuse cycles, skip
 *  the fresh unless forced, run jobs in dependency order as the caller. A job
 *  whose inputs another unfinished build is rewriting stays WAITING and the
 *  build stays RUNNING — the queue the page describes. NULL means everything
 *  was fresh and no build was created.
 */
export const runBuild = { apiName: 'run_build', kind: 'action' } as ActionType<
  { p_targets: string[]; p_force?: boolean; p_build_type?: string; p_schedule?: string; p_abort_on_failure?: boolean },
  string
>

export const runBuildJob = { apiName: 'run_build_job', kind: 'action' } as ActionType<
  { p_job: string },
  string
>

/**
 *  One build whose jobs index object types. Foundry indexes through build
 *  jobs; a job waits for any unfinished build rewriting its datasources. NULL
 *  means every index was fresh.
 */
export const runIndexBuild = { apiName: 'run_index_build', kind: 'action' } as ActionType<
  { p_types: string[]; p_force?: boolean },
  string
>

export const runObjectDatasetBuild = { apiName: 'run_object_dataset_build', kind: 'action' } as ActionType<
  { p_object_dataset: string; p_force?: boolean },
  string
>

/**
 *  The Actions sub-tab's writer: the satisfaction and its
 *  Configure-parameters mappings in one transaction, so 467's commit-time
 *  completeness judges the whole. Re-satisfying replaces the mappings
 *  wholesale.
 */
export const satisfyActionConstraint = { apiName: 'satisfy_action_constraint', kind: 'action' } as ActionType<
  { p_object_type: string; p_interface: string; p_constraint: string; p_action_type: string; p_mappings?: Json },
  void
>

export const saveActionType = { apiName: 'save_action_type', kind: 'action' } as ActionType<
  { p_action: Json; p_branch?: string },
  string
>

export const saveInterface = { apiName: 'save_interface', kind: 'action' } as ActionType<
  { p_interface: Json; p_branch?: string },
  string
>

export const saveLinkType = { apiName: 'save_link_type', kind: 'action' } as ActionType<
  { p_link: Json; p_branch?: string },
  string
>

/**
 *  Save the current exploration as a dynamic Exploration or a static List,
 *  into a project the caller can edit. A list without an explicit selection
 *  snapshots the filtered results at this moment.
 */
export const saveObjectSet = { apiName: 'save_object_set', kind: 'action' } as ActionType<
  { p_set: Json },
  string
>

export const saveObjectType = { apiName: 'save_object_type', kind: 'action' } as ActionType<
  { p_object_type: Json; p_properties: Json; p_branch?: string },
  string
>

export const saveSharedProperty = { apiName: 'save_shared_property', kind: 'action' } as ActionType<
  { p_property: Json; p_branch?: string },
  string
>

/**
 *  "Save to new branch from the save dialog": create the branch in the
 *  working state's ontology, move the caller's unsaved entries onto it, and
 *  run the branch save. Atomic — a failed save rolls the branch back too.
 */
export const saveToNewBranch = { apiName: 'save_to_new_branch', kind: 'action' } as ActionType<
  { p_name: string; p_title?: string },
  string
>

/**
 *  Save the working state. On main: apply, validate the delta, bump the
 *  version, clear the entries. On a branch: validate the same way against the
 *  COMPOSED overlay (rolled back), then promote the entries into
 *  branch_resource_changes — main's tables are never touched, the
 *  total-overlay rule for ontology resources.
 */
export const saveWorkingState = { apiName: 'save_working_state', kind: 'action' } as ActionType<
  { p_branch?: string },
  number
>

export const settleBuild = { apiName: 'settle_build', kind: 'action' } as ActionType<
  { p_build: string },
  string
>

/**
 *  Put an edit in my working state instead of writing it through. Captures
 *  the base on first touch only — re-reading it would silently adopt someone
 *  else's save as my starting point and the conflict would disappear rather
 *  than be shown.
 */
export const stageChange = { apiName: 'stage_change', kind: 'action' } as ActionType<
  { p_kind: string; p_id: string; p_fields: Json; p_branch?: string; p_operation?: string },
  string
>

/**
 *  Pull the latest ontology into my working state. Re-bases every staged
 *  field to what the ontology holds now; a resolution of latest drops my
 *  value for the fields we both moved, mine keeps it as an override. One
 *  choice per resource, because the conflict dialog offers one pair of
 *  buttons per entity even though it lists the fields.
 */
export const updateWorkingState = { apiName: 'update_working_state', kind: 'action' } as ActionType<
  { p_resolutions?: Json; p_branch?: string },
  number
>

// ── FUNCTIONS (160) ───────────────────────────────────────────────────
// Stable or immutable: they read and return.

/**
 *  Objects editable in one action: "enabling up to 10,000 objects to be
 *  edited in a single Action" (object-backend/overview).
 */
export const actionEditLimit = { apiName: 'action_edit_limit', kind: 'function' } as FunctionType<
  Record<string, never>,
  number
>

/**
 *  Every property this action type can write. An interface rule expands to
 *  the concrete property each implementing type mapped its interface property
 *  onto, skipping types that turned interface actions off — because the
 *  action edits objects, and an interface has none.
 */
export const actionEditableProperties = { apiName: 'action_editable_properties', kind: 'function' } as FunctionType<
  { p_action: string },
  { object_type: string; property: string; rule_kind: string }[]
>

export const actionFunctionToRun = { apiName: 'action_function_to_run', kind: 'function' } as FunctionType<
  { p_action_type: string },
  Json
>

/**
 *  The seven rule kinds (action-types/rules.md), what each targets, whether
 *  it can be applied, and which runtime applies it. The five interface kinds
 *  and three side-effect kinds are deliberately absent, as 418 records.
 */
export const actionRuleKinds = { apiName: 'action_rule_kinds', kind: 'function' } as FunctionType<
  Record<string, never>,
  { kind: string; targets: string; executable: boolean; runtime: string; note: string }[]
>

/**
 *  The function version a function-backed action runs: the pinned one, or
 *  with auto_upgrade the maximum version satisfying the caret range on it.
 */
export const actionRuleVersion = { apiName: 'action_rule_version', kind: 'function' } as FunctionType<
  { p_rule: string },
  string
>

export const activeScopedSession = { apiName: 'active_scoped_session', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

/**
 *  One shape for listogram, Single Statistic and Statistics Table:
 *  group_value plus Count/Sum/Average/Min/Max/Property Count/Unique Count.
 *  Unique count is exact, not estimated.
 */
export const aggregateObjectSet = { apiName: 'aggregate_object_set', kind: 'function' } as FunctionType<
  { p_object_type: string; p_filters?: Json; p_group_by?: string; p_agg_property?: string; p_sort_by?: string; p_desc?: boolean; p_limit?: number },
  { group_value: string; object_count: number; sum: number; average: number; min: number; max: number; property_count: number; unique_count: number }[]
>

export const authGroupIds = { apiName: 'auth_group_ids', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

export const authGroupNames = { apiName: 'auth_group_names', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

/**
 *  May this session SEE the ontology: some organization I am a member or
 *  guest of is in its space's list. "Users need permission from at least one
 *  organization to access this space."
 */
export const authInOntology = { apiName: 'auth_in_ontology', kind: 'function' } as FunctionType<
  { p_ontology: string },
  boolean
>

/**
 *  "users must be a member or guest member of at least one organization
 *  applied to a Project" — this is that sentence. Note it is false for a NULL
 *  organization, where the old IS NOT DISTINCT FROM comparison was true for a
 *  session that had none.
 */
export const authInOrg = { apiName: 'auth_in_org', kind: 'function' } as FunctionType<
  { p_org: string },
  boolean
>

export const authMarkingIds = { apiName: 'auth_marking_ids', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

/**
 *  May this session WRITE in the ontology (role checks apply on top): my
 *  primary organization is in its space's list. Guests read; members write.
 */
export const authMemberOfOntology = { apiName: 'auth_member_of_ontology', kind: 'function' } as FunctionType<
  { p_ontology: string },
  boolean
>

/**
 *  Current user's organization scope. Mirrors auth_hotel_id(). JWT claim
 *  takes precedence; falls back to parent org of hotel.
 */
export const authOrgId = { apiName: 'auth_org_id', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

/**
 *  Every organization this session can meet an access requirement with: the
 *  one primary membership plus any guest memberships. Read from the token —
 *  the access token hook derives both from the database at issue.
 */
export const authOrgIds = { apiName: 'auth_org_ids', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

export const authOrgMarkingIds = { apiName: 'auth_org_marking_ids', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

export const authRole = { apiName: 'auth_role', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

export const automationConditionValid = { apiName: 'automation_condition_valid', kind: 'function' } as FunctionType<
  { p: Json },
  boolean
>

export const automationEffectKinds = { apiName: 'automation_effect_kinds', kind: 'function' } as FunctionType<
  Record<string, never>,
  { kind: string; runtime: string; executable: boolean; note: string }[]
>

/**
 *  Whether a failure is one the page calls retryable: rate limits, service
 *  outages, and ephemeral errors such as Actions:ObjectVersionChanged.
 */
export const automationErrorRetryable = { apiName: 'automation_error_retryable', kind: 'function' } as FunctionType<
  { p_error: string },
  boolean
>

export const automationFires = { apiName: 'automation_fires', kind: 'function' } as FunctionType<
  { p_automation: string; p_at: string },
  string[]
>

/**
 *  The published maximum input size for a scheduled object-set condition:
 *  1,000,000 for Run on all objects, 100,000 for Objects added and Objects
 *  removed.
 */
export const automationInputLimit = { apiName: 'automation_input_limit', kind: 'function' } as FunctionType<
  { p_condition_type: string },
  number
>

export const automationRetryDue = { apiName: 'automation_retry_due', kind: 'function' } as FunctionType<
  { p_effect: string; p_attempt: number },
  string
>

/**
 *  Every field both this branch and main have moved since the branch recorded
 *  its base. Everything not listed auto-resolves on rebase, which is what
 *  Global Branching does.
 */
export const branchConflicts = { apiName: 'branch_conflicts', kind: 'function' } as FunctionType<
  { p_branch: string },
  { resource_kind: string; resource_id: string; field: string; base_value: Json; branch_value: Json; main_value: Json }[]
>

export const buildFieldOf = { apiName: 'build_field_of', kind: 'function' } as FunctionType<
  { p_pg_type: string },
  Json
>

export const canApplyMarking = { apiName: 'can_apply_marking', kind: 'function' } as FunctionType<
  { p_marking: string },
  boolean
>

export const canChooseScopedSession = { apiName: 'can_choose_scoped_session', kind: 'function' } as FunctionType<
  { p_session: string },
  boolean
>

export const canCuratePortfolio = { apiName: 'can_curate_portfolio', kind: 'function' } as FunctionType<
  { p_portfolio: string },
  boolean
>

export const canIndexObjectType = { apiName: 'can_index_object_type', kind: 'function' } as FunctionType<
  { p_type: string },
  boolean
>

export const canManageBranch = { apiName: 'can_manage_branch', kind: 'function' } as FunctionType<
  { p_branch: string },
  boolean
>

export const canManageMarking = { apiName: 'can_manage_marking', kind: 'function' } as FunctionType<
  { p_marking: string },
  boolean
>

export const canManagePortfolio = { apiName: 'can_manage_portfolio', kind: 'function' } as FunctionType<
  { p_portfolio: string },
  boolean
>

export const canReadActionType = { apiName: 'can_read_action_type', kind: 'function' } as FunctionType<
  { p_action: string },
  boolean
>

/**
 *  FILE access: same organization, and a member of every file marking. Gates
 *  the registry row, the schema and the transaction history — not the rows.
 */
export const canReadDataset = { apiName: 'can_read_dataset', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

/**
 *  DATA access: file access plus every data marking propagated from upstream.
 *  Gates rows only.
 */
export const canReadDatasetData = { apiName: 'can_read_dataset_data', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

export const canRemoveMarking = { apiName: 'can_remove_marking', kind: 'function' } as FunctionType<
  { p_marking: string },
  boolean
>

export const canSeeBranch = { apiName: 'can_see_branch', kind: 'function' } as FunctionType<
  { p_branch: string },
  boolean
>

export const canSeeMarkingCategory = { apiName: 'can_see_marking_category', kind: 'function' } as FunctionType<
  { p_category: string },
  boolean
>

export const canSeePlaced = { apiName: 'can_see_placed', kind: 'function' } as FunctionType<
  { p_project: string },
  boolean
>

export const canSeeProposal = { apiName: 'can_see_proposal', kind: 'function' } as FunctionType<
  { p_proposal: string },
  boolean
>

export const canWriteActionType = { apiName: 'can_write_action_type', kind: 'function' } as FunctionType<
  { p_action: string },
  boolean
>

/**
 *  Same organization, an editor role, AND membership of every file marking.
 *  The marking term is not redundant with can_read_dataset: a role can never
 *  override a mandatory control, so it is stated on both sides.
 */
export const canWriteDataset = { apiName: 'can_write_dataset', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

export const canWriteDatasetData = { apiName: 'can_write_dataset_data', kind: 'function' } as FunctionType<
  { p_dataset: string },
  boolean
>

/**
 *  The slot-based Capabilities vocabulary, from metadata-typeclasses (the
 *  page it replaces) and the Geospatial panel screenshot. Time series is the
 *  other panel shape and lives in time_series_properties.
 */
export const capabilitySlots = { apiName: 'capability_slots', kind: 'function' } as FunctionType<
  Record<string, never>,
  { capability: string; slot: string; accepts: string[]; note: string }[]
>

/**
 *  The Check access panel: Access requirements (organization, markings, roles
 *  with their source) and Additional data requirements (markings inherited
 *  through lineage), verdict per clause, for any named user.
 */
export const checkAccess = { apiName: 'check_access', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string; p_user: string },
  { section: string; requirement: string; detail: string; satisfied: boolean }[]
>

export const compassProjectOf = { apiName: 'compass_project_of', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string },
  string
>

/**
 *  The Results count over the same WHERE the rows use.
 */
export const countObjectSet = { apiName: 'count_object_set', kind: 'function' } as FunctionType<
  { p_object_type: string; p_filters?: Json },
  number
>

export const countObjectSetByApiName = { apiName: 'count_object_set_by_api_name', kind: 'function' } as FunctionType<
  { p_ontology: string; p_api_name: string; p_filters?: Json },
  number
>

/**
 *  The message shown when this criterion fails: its own if it is root-level,
 *  otherwise its root ancestor's.
 */
export const criterionFailureMessage = { apiName: 'criterion_failure_message', kind: 'function' } as FunctionType<
  { p_node: string },
  string
>

export const cronFieldMatches = { apiName: 'cron_field_matches', kind: 'function' } as FunctionType<
  { p_field: string; p_value: number; p_min: number; p_max: number },
  boolean
>

export const cronMatches = { apiName: 'cron_matches', kind: 'function' } as FunctionType<
  { p_cron: string; p_tz: string; p_at: string },
  boolean
>

/**
 *  The schema in force on a branch: the nearest one down the commit chain
 *  from its head. Per branch, because a datasource is a dataset ON A BRANCH.
 */
export const datasetBranchSchema = { apiName: 'dataset_branch_schema', kind: 'function' } as FunctionType<
  { p_branch: string },
  Json
>

export const datasetCurrentFields = { apiName: 'dataset_current_fields', kind: 'function' } as FunctionType<
  { p_dataset: string },
  Json
>

export const datasetFieldSqlType = { apiName: 'dataset_field_sql_type', kind: 'function' } as FunctionType<
  { f: Json },
  string
>

export const datasetFieldValid = { apiName: 'dataset_field_valid', kind: 'function' } as FunctionType<
  { f: Json },
  boolean
>

export const datasetHistory = { apiName: 'dataset_history', kind: 'function' } as FunctionType<
  { p_branch: string; p_at?: string },
  { transaction_id: string; txn_type: string; committed_at: string; seq: number }[]
>

export const datasetHistoryFrom = { apiName: 'dataset_history_from', kind: 'function' } as FunctionType<
  { p_transaction: string; p_at?: string },
  { transaction_id: string; txn_type: string; committed_at: string; seq: number }[]
>

export const datasetMarkings = { apiName: 'dataset_markings', kind: 'function' } as FunctionType<
  { p_dataset: string },
  { marking_id: string; name: string; category: string; kind: string; origin: string; satisfied: boolean }[]
>

/**
 *  The caller's role on a dataset, inherited from the project that holds it.
 */
export const datasetRole = { apiName: 'dataset_role', kind: 'function' } as FunctionType<
  { p_dataset: string },
  string
>

/**
 *  A tabular dataset schema: an array of uniquely-named fields whose types
 *  are the fifteen from data-integration/datasets, with the four
 *  parameterised ones carrying their parameters.
 */
export const datasetSchemaValid = { apiName: 'dataset_schema_valid', kind: 'function' } as FunctionType<
  { fields: Json },
  boolean
>

/**
 *  The current view of a branch, or the view at a point in time. For "as of
 *  transaction X" use dataset_view_from, which cannot be truncated.
 */
export const datasetView = { apiName: 'dataset_view', kind: 'function' } as FunctionType<
  { p_branch: string; p_at?: string },
  { file_id: string; logical_path: string; row_count: number }[]
>

/**
 *  The view as of a transaction — the precision-safe anchor. Prefer this over
 *  a client-supplied timestamp: a JS Date truncates timestamptz to
 *  milliseconds and drops the transaction it names.
 */
export const datasetViewFrom = { apiName: 'dataset_view_from', kind: 'function' } as FunctionType<
  { p_transaction: string; p_at?: string },
  { file_id: string; logical_path: string; row_count: number }[]
>

export const datasetViewTransactions = { apiName: 'dataset_view_transactions', kind: 'function' } as FunctionType<
  { p_branch: string; p_at?: string },
  { transaction_id: string; txn_type: string; seq: number }[]
>

export const datasetViewTransactionsFrom = { apiName: 'dataset_view_transactions_from', kind: 'function' } as FunctionType<
  { p_transaction: string; p_at?: string },
  { transaction_id: string; txn_type: string; seq: number }[]
>

/**
 *  The caller organization's ontology when it has exactly one. Raises rather
 *  than guessing when there are none or several — the Ontology Manager picker
 *  is a choice, and a silent wrong guess writes to the wrong ontology.
 */
export const defaultOntology = { apiName: 'default_ontology', kind: 'function' } as FunctionType<
  Record<string, never>,
  string
>

/**
 *  The file markings of every transitive input, arriving here as data
 *  markings. A union over inputs: one marked input marks everything
 *  downstream.
 */
export const effectiveDataMarkings = { apiName: 'effective_data_markings', kind: 'function' } as FunctionType<
  { p_dataset: string },
  string[]
>

/**
 *  Which markings a resource demands by the file route. SECURITY DEFINER
 *  because it reads `datasets` to resolve project inheritance, and is itself
 *  called from the datasets policy — invoker rights recurse.
 */
export const effectiveFileMarkings = { apiName: 'effective_file_markings', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string },
  string[]
>

/**
 *  One node of the submission criteria tree, depth first. A condition it
 *  cannot evaluate raises by name — the gate never silently passes what it
 *  cannot parse.
 */
export const evalCriterion = { apiName: 'eval_criterion', kind: 'function' } as FunctionType<
  { p_node: string; p_action: string; p_params: Json },
  unknown
>

/**
 *  The exploration engine's row reader: documented filters in, index rows out
 *  as jsonb, hidden properties stripped, multi-sort applied in order.
 */
export const evaluateObjectSet = { apiName: 'evaluate_object_set', kind: 'function' } as FunctionType<
  { p_object_type: string; p_filters?: Json; p_sort?: Json; p_limit?: number; p_offset?: number },
  Json[]
>

/**
 *  The exploration reader addressed the way the generated client addresses
 *  it: by api name. Every gate the id form carries still applies.
 */
export const evaluateObjectSetByApiName = { apiName: 'evaluate_object_set_by_api_name', kind: 'function' } as FunctionType<
  { p_ontology: string; p_api_name: string; p_filters?: Json; p_limit?: number },
  Json[]
>

/**
 *  direct = applied on this resource; file_hierarchy = inherited from its
 *  project. Foundry renders the second with a folder sidecar icon on the
 *  chip.
 */
export const fileMarkingOrigin = { apiName: 'file_marking_origin', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string; p_marking: string },
  string
>

export const folderInTrash = { apiName: 'folder_in_trash', kind: 'function' } as FunctionType<
  { p_folder: string },
  boolean
>

export const functionEditsValid = { apiName: 'function_edits_valid', kind: 'function' } as FunctionType<
  { p_sig: Json; p_edits: Json },
  boolean
>

/**
 *  The latest version of a function: the highest semantic version excluding
 *  prereleases by default, or the most recently published one including them
 *  when resolution is PUBLISH_TIME.
 */
export const functionLatestVersion = { apiName: 'function_latest_version', kind: 'function' } as FunctionType<
  { p_function: string; p_resolution?: string; p_include_prerelease?: boolean },
  string
>

/**
 *  The version a caller meant: the one they pinned, or the latest under the
 *  given resolution. Refuses includePrerelease alongside an explicit version,
 *  which the API does not support.
 */
export const functionResolveVersion = { apiName: 'function_resolve_version', kind: 'function' } as FunctionType<
  { p_function: string; p_version?: string; p_resolution?: string; p_include_prerelease?: boolean },
  string
>

export const functionSignatureValid = { apiName: 'function_signature_valid', kind: 'function' } as FunctionType<
  { p_sig: Json },
  boolean
>

export const functionToRun = { apiName: 'function_to_run', kind: 'function' } as FunctionType<
  { p_ontology: string; p_api_name: string; p_version?: string; p_resolution?: string; p_include_prerelease?: boolean },
  Json
>

/**
 *  Whether a token may appear in a published v2 function signature. The
 *  spellings are TypeScript v2's: DateISOString and TimestampISOString, not
 *  v1's LocalDate and Timestamp.
 */
export const functionTypeValid = { apiName: 'function_type_valid', kind: 'function' } as FunctionType<
  { p_type: string },
  boolean
>

/**
 *  A function version as the API writes it: <major>.<minor>.<patch>-<tag>,
 *  the tag optional.
 */
export const functionVersionString = { apiName: 'function_version_string', kind: 'function' } as FunctionType<
  { p_major: number; p_minor: number; p_patch: number; p_prerelease?: string },
  string
>

/**
 *  Privileges an application role holds that no policy can restrain. TRUNCATE
 *  is the dangerous one: row-level security does not apply to it.
 */
export const grantViolations = { apiName: 'grant_violations', kind: 'function' } as FunctionType<
  Record<string, never>,
  { relation: string; grantee: string; privilege: string; problem: string }[]
>

export const granularComparisonCheck = { apiName: 'granular_comparison_check', kind: 'function' } as FunctionType<
  { p_comp: Json; p_fields: Json },
  unknown
>

/**
 *  One comparison as SQL. An unbound user attribute compiles to false rather
 *  than to a placeholder value, because a placeholder leaves the outcome to
 *  the operator and the empty set is a subset of everything.
 */
export const granularComparisonSql = { apiName: 'granular_comparison_sql', kind: 'function' } as FunctionType<
  { p_comp: Json; p_fields: Json; p_alias: string },
  string
>

/**
 *  Validates a granular policy against the backing dataset's schema: the
 *  eight comparisons with their arity, the 1/1,000/3,000 weights capped under
 *  10,000, at most ten comparisons, at least one user attribute, and no NOT.
 */
export const granularPolicyCheck = { apiName: 'granular_policy_check', kind: 'function' } as FunctionType<
  { p_policy: Json; p_fields: Json },
  void
>

/**
 *  "The template is converted into a query": the validated policy compiled to
 *  a WHERE fragment over the backing dataset's materialized table, caller
 *  attributes as function calls evaluated at query time.
 */
export const granularPolicySql = { apiName: 'granular_policy_sql', kind: 'function' } as FunctionType<
  { p_policy: Json; p_fields: Json; p_alias: string },
  string
>

export const granularTermShape = { apiName: 'granular_term_shape', kind: 'function' } as FunctionType<
  { p_term: Json; p_fields: Json },
  { kind: string; is_collection: boolean; is_marking: boolean }[]
>

export const granularTermSql = { apiName: 'granular_term_sql', kind: 'function' } as FunctionType<
  { p_term: Json; p_fields: Json; p_alias: string },
  unknown
>

export const hasGroupPermission = { apiName: 'has_group_permission', kind: 'function' } as FunctionType<
  { p_group: string; p_permission: string },
  boolean
>

export const hasOrgWorkflow = { apiName: 'has_org_workflow', kind: 'function' } as FunctionType<
  { p_organization: string; p_workflow: string },
  boolean
>

export const hasResourceRole = { apiName: 'has_resource_role', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string; p_min: string },
  boolean
>

export const hasSpaceWorkflow = { apiName: 'has_space_workflow', kind: 'function' } as FunctionType<
  { p_space: string; p_workflow: string },
  boolean
>

/**
 *  Histogram buckets over a numeric or date property of the filtered set;
 *  bounds from the data, bucket count from the caller.
 */
export const histogramObjectSet = { apiName: 'histogram_object_set', kind: 'function' } as FunctionType<
  { p_object_type: string; p_filters?: Json; p_property?: string; p_buckets?: number },
  { bucket_min: number; bucket_max: number; object_count: number }[]
>

export const holdsMarkingPermission = { apiName: 'holds_marking_permission', kind: 'function' } as FunctionType<
  { p_marking: string; p_user: string; p_permission: string },
  boolean
>

export const indexedObjects = { apiName: 'indexed_objects', kind: 'function' } as FunctionType<
  { p_object_type: string; p_limit?: number },
  Json[]
>

export const interfaceAncestors = { apiName: 'interface_ancestors', kind: 'function' } as FunctionType<
  { p_interface: string },
  string[]
>

export const isCategoryAdmin = { apiName: 'is_category_admin', kind: 'function' } as FunctionType<
  { p_category: string },
  boolean
>

/**
 *  The unfinished build whose output is one of this job's inputs, or NULL. A
 *  job with one waits rather than reading data that is about to change.
 */
export const jobBlockedBy = { apiName: 'job_blocked_by', kind: 'function' } as FunctionType<
  { p_job: string },
  string
>

export const jobSpecFresh = { apiName: 'job_spec_fresh', kind: 'function' } as FunctionType<
  { p_spec: string },
  boolean
>

export const jobSpecInputState = { apiName: 'job_spec_input_state', kind: 'function' } as FunctionType<
  { p_spec: string },
  Json
>

export const jobSpecQuery = { apiName: 'job_spec_query', kind: 'function' } as FunctionType<
  { p_spec: string },
  string
>

export const jobSpecQueryText = { apiName: 'job_spec_query_text', kind: 'function' } as FunctionType<
  { p_output: string; p_logic: string },
  string
>

/**
 *  The schema version of a JobSpec's pipeline: its own for a dataset spec,
 *  the object type's for an index spec. A job recorded at an older one is
 *  running an out-of-date pipeline.
 */
export const jobSpecVersion = { apiName: 'job_spec_version', kind: 'function' } as FunctionType<
  { p_spec: string },
  number
>

/**
 *  The generated accessor for one end of a link type: .get() where that side
 *  sees one, .all() where it sees many. Derived from cardinality so the two
 *  can never disagree.
 */
export const linkAccessor = { apiName: 'link_accessor', kind: 'function' } as FunctionType<
  { p_link: string; p_side: string },
  string
>

export const markingMember = { apiName: 'marking_member', kind: 'function' } as FunctionType<
  { p_marking: string; p_user: string },
  boolean
>

export const objectDatasetBuiltAt = { apiName: 'object_dataset_built_at', kind: 'function' } as FunctionType<
  { p_dataset: string },
  string
>

/**
 *  The filter grammar generate-urls.md prints: propertyFilter with seven
 *  value kinds, at most one linkFilter carrying a presenceFilter.
 */
export const objectSetFiltersValid = { apiName: 'object_set_filters_valid', kind: 'function' } as FunctionType<
  { p: Json },
  boolean
>

export const objectSetKeys = { apiName: 'object_set_keys', kind: 'function' } as FunctionType<
  { p_set: string; p_limit?: number },
  string[]
>

/**
 *  A saved set's objects: an exploration re-evaluates its filters; a list
 *  resolves its stored membership through the same engine path.
 */
export const objectSetRows = { apiName: 'object_set_rows', kind: 'function' } as FunctionType<
  { p_set: string; p_limit?: number; p_offset?: number },
  Json[]
>

/**
 *  How many objects a saved set holds right now — live for an exploration,
 *  stored for a list.
 */
export const objectSetSize = { apiName: 'object_set_size', kind: 'function' } as FunctionType<
  { p_set: string },
  number
>

/**
 *  Grammar for object_sets.traversals — every element is {edgeType,
 *  direction: forward|reverse, filters?}, at most 3 hops (Foundry caps Search
 *  Around depth at 3).
 */
export const objectSetTraversalsValid = { apiName: 'object_set_traversals_valid', kind: 'function' } as FunctionType<
  { p: Json },
  boolean
>

/**
 *  Resolves one object from its datasource row and its edit log, following
 *  the four-step decision in object-edits/how-edits-applied. Checked against
 *  that page's T0–T14 table in @beacon/platform.
 */
export const objectState = { apiName: 'object_state', kind: 'function' } as FunctionType<
  { p_object_type: string; p_primary_key: string; p_datasource_row: Json },
  { properties: Json; deleted: boolean }[]
>

/**
 *  Whether an object type can be read: its last index build job COMPLETED.
 *  The legacy scalar is no longer consulted — since 532 an index is only ever
 *  produced by a build job.
 */
export const objectTypeIndexReady = { apiName: 'object_type_index_ready', kind: 'function' } as FunctionType<
  { p_type: string },
  boolean
>

/**
 *  One row per index: the last build job's state and error, with the row
 *  count and time. The OSv2 answer to what the Index status scalar used to
 *  show.
 */
export const objectTypeIndexReport = { apiName: 'object_type_index_report', kind: 'function' } as FunctionType<
  Record<string, never>,
  { object_type_id: string; state: string; error: string; object_count: number; indexed_at: string }[]
>

/**
 *  The state of the last index build job for this object type, in the seven
 *  documented job states. OSv2 has no scalar index status: "a dedicated
 *  pipeline graph that shows the status of various jobs in a Funnel pipeline"
 *  is the surface.
 */
export const objectTypeIndexState = { apiName: 'object_type_index_state', kind: 'function' } as FunctionType<
  { p_type: string },
  string
>

/**
 *  The datasets an object type reads, one per datasource, resolving a
 *  restricted-view backing to the view's backing dataset: "Backing dataset:
 *  The backing dataset of the restricted view."
 */
export const objectTypeInputDatasets = { apiName: 'object_type_input_datasets', kind: 'function' } as FunctionType<
  { p_type: string },
  string[]
>

/**
 *  Every reason an object type cannot be saved, from the two lists in
 *  create-object-type#mandatory-object-type-fields. This is what the "4
 *  errors" badge counts.
 */
export const objectTypeProblems = { apiName: 'object_type_problems', kind: 'function' } as FunctionType<
  { p_object_type: string },
  { scope: string; subject: string; problem: string }[]
>

/**
 *  A column's type, for casting a jsonb ->> back into it. The working state
 *  stores values as jsonb; every column that is not text needs the cast the
 *  catalogue names.
 */
export const ontologyColumnType = { apiName: 'ontology_column_type', kind: 'function' } as FunctionType<
  { p_table: string; p_column: string },
  string
>

/**
 *  A resource as jsonb, in the shape the Review edits dialog shows it — for
 *  an object type that includes its properties, which the dialog renders as a
 *  section inside the type's entry rather than as entries of their own.
 */
export const ontologyResourceRow = { apiName: 'ontology_resource_row', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string },
  Json
>

export const ontologyRole = { apiName: 'ontology_role', kind: 'function' } as FunctionType<
  { p_ontology: string },
  string
>

/**
 *  Every well-formedness violation in the ontology, as rows. The linting half
 *  of what check:platform was doing by assertion — see
 *  superrepo/core-concepts "Ontology linting".
 */
export const ontologyViolations = { apiName: 'ontology_violations', kind: 'function' } as FunctionType<
  Record<string, never>,
  { object_type: string; scope: string; subject: string; problem: string }[]
>

export const opensearchAnalyzer = { apiName: 'opensearch_analyzer', kind: 'function' } as FunctionType<
  { p_analyzer: string },
  string
>

/**
 *  The workflows the caller holds in one organization, through roles granted
 *  to them or to a group they are in. An Organization administrator
 *  incorporates all workflows except the legacy application-specific ones.
 */
export const orgWorkflows = { apiName: 'org_workflows', kind: 'function' } as FunctionType<
  { p_organization: string },
  string[]
>

/**
 *  Disjunctive: passes when there is no session, when the resource has no
 *  markings, or when the resource carries at least one of the session's
 *  markings. Stacks on top of the conjunctive satisfies_markings — it does
 *  not replace it.
 */
export const passesScopedSession = { apiName: 'passes_scoped_session', kind: 'function' } as FunctionType<
  { p_markings: string[] },
  boolean
>

/**
 *  Resources of the portfolio's member projects. SECURITY INVOKER on purpose:
 *  the caller sees only the projects and resources their own grants allow,
 *  which is what keeps a portfolio curation rather than access.
 */
export const portfolioCatalog = { apiName: 'portfolio_catalog', kind: 'function' } as FunctionType<
  { p_portfolio: string },
  { project_id: string; project_name: string; resource_kind: string; resource_id: string }[]
>

export const primaryKeyAdvice = { apiName: 'primary_key_advice', kind: 'function' } as FunctionType<
  { p_base_type: string },
  string
>

/**
 *  yes | discouraged | no, from properties-overview. Only `no` is a
 *  constraint; `discouraged` is a warning carrying primary_key_advice().
 */
export const primaryKeyEligibility = { apiName: 'primary_key_eligibility', kind: 'function' } as FunctionType<
  { p_base_type: string },
  string
>

/**
 *  The caller's strongest role on one project — direct, via a group, or the
 *  project default — in any organization they belong to. SECURITY DEFINER
 *  because a predicate that decides access may not be subject to it, and
 *  because the grants policy calls this function.
 */
export const projectRole = { apiName: 'project_role', kind: 'function' } as FunctionType<
  { p_project: string },
  string
>

export const propertyBaseTypes = { apiName: 'property_base_types', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

export const propertyColumnType = { apiName: 'property_column_type', kind: 'function' } as FunctionType<
  { p_base_type: string },
  string
>

export const propertyDatasetFieldType = { apiName: 'property_dataset_field_type', kind: 'function' } as FunctionType<
  { p_base_type: string },
  string
>

/**
 *  Every reason this proposal cannot merge. Empty means it can. Approval and
 *  merge checks are separate reasons — a task can be approved and still fail
 *  its check.
 */
export const proposalBlockers = { apiName: 'proposal_blockers', kind: 'function' } as FunctionType<
  { p_proposal: string },
  { scope: string; subject: string; reason: string }[]
>

export const reservedApiNames = { apiName: 'reserved_api_names', kind: 'function' } as FunctionType<
  Record<string, never>,
  string[]
>

/**
 *  The single definition of file access: same organization, a member of every
 *  file marking, and inside the scoped session. Every policy and helper
 *  composes this rather than restating it — restating it is what produced
 *  migrations 395 and 403.
 */
export const resourceFileAccess = { apiName: 'resource_file_access', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string; p_org: string },
  boolean
>

/**
 *  A resource's filepath: /<space path>/<project>/<name>. Falls back to
 *  /<project>/<name> while a project has no space, which is the pre-397
 *  shape.
 */
export const resourceLocation = { apiName: 'resource_location', kind: 'function' } as FunctionType<
  { p_project: string; p_name: string },
  string
>

export const resourceProject = { apiName: 'resource_project', kind: 'function' } as FunctionType<
  { p_kind: string; p_id: string },
  unknown
>

export const restrictedViewMarkings = { apiName: 'restricted_view_markings', kind: 'function' } as FunctionType<
  { p_view: string },
  string[]
>

/**
 *  The policy gate for one object type, or NULL when it is not
 *  restricted-view-backed. The index stays whole; this is the only door.
 */
export const restrictedViewPredicate = { apiName: 'restricted_view_predicate', kind: 'function' } as FunctionType<
  { p_object_type: string },
  string
>

/**
 *  The <locator> of a RID: everything after the fourth separator, because the
 *  locator may itself contain dots (palantir/resource-identifier). NULL when
 *  malformed or not a uuid.
 */
export const ridLocator = { apiName: 'rid_locator', kind: 'function' } as FunctionType<
  { p_rid: string },
  string
>

export const roleRank = { apiName: 'role_rank', kind: 'function' } as FunctionType<
  { p_role: string },
  number
>

/**
 *  Conjunctive: "a user must be a member of ALL the Markings on a file,
 *  folder, or Project". Empty set passes — no markings is not a restriction.
 */
export const satisfiesMarkings = { apiName: 'satisfies_markings', kind: 'function' } as FunctionType<
  { p_markings: string[] },
  boolean
>

export const scheduleObserve = { apiName: 'schedule_observe', kind: 'function' } as FunctionType<
  { p_trigger: Json; p_state: Json },
  Json
>

export const scheduleSatisfied = { apiName: 'schedule_satisfied', kind: 'function' } as FunctionType<
  { p_trigger: Json; p_state: Json; p_at: string },
  boolean
>

export const scheduleTriggerValid = { apiName: 'schedule_trigger_valid', kind: 'function' } as FunctionType<
  { p: Json },
  boolean
>

/**
 *  Jump-to object search: titles only, from the index, across up to 250
 *  visible object types in the documented priority
 *  (promoted/active-prominent, active, experimental; deprecated and hidden
 *  excluded). Definer because the objects schema takes no grants;
 *  auth_in_ontology() gates every type.
 */
export const searchObjects = { apiName: 'search_objects', kind: 'function' } as FunctionType<
  { p_query: string; p_limit?: number },
  { object_type_id: string; object_type_label: string; primary_key: string; title: string }[]
>

/**
 *  The caller's searchable types in quicksearch's documented priority order
 *  (443) — the query-side edge function's scope, evaluated with the caller's
 *  own claims.
 */
export const searchVisibleTypes = { apiName: 'search_visible_types', kind: 'function' } as FunctionType<
  Record<string, never>,
  { object_type_id: string; object_type_label: string; index_table: string; title_property: string; primary_key_property: string }[]
>

export const selectableScopedSessions = { apiName: 'selectable_scoped_sessions', kind: 'function' } as FunctionType<
  Record<string, never>,
  { id: string; name: string; description: string; markings: string[] }[]
>

/**
 *  The exclusive upper bound of a caret range: the backward-compatible window
 *  an auto-upgrading dependency may move within.
 */
export const semverCaretUpper = { apiName: 'semver_caret_upper', kind: 'function' } as FunctionType<
  { p_major: number; p_minor: number; p_patch: number },
  number[]
>

/**
 *  A sortable key for a prerelease tag. INFERENCE: the documentation gives
 *  the tag format but no ordering between two prereleases of one version.
 */
export const semverPrereleaseKey = { apiName: 'semver_prerelease_key', kind: 'function' } as FunctionType<
  { p_prerelease: string },
  string[]
>

/**
 *  The documented breaking changes between two signatures: dropped, moved,
 *  retyped or newly-required inputs, and output changes. Widening a numeric
 *  input is not a break.
 */
export const signatureBreaks = { apiName: 'signature_breaks', kind: 'function' } as FunctionType<
  { p_old: Json; p_new: Json },
  string[]
>

/**
 *  Rehearse a marking change before applying it: the four documented states
 *  per downstream dataset, with removals allowed only on directly-applied
 *  markings. Hypothetical — nothing is written.
 */
export const simulateMarkingChanges = { apiName: 'simulate_marking_changes', kind: 'function' } as FunctionType<
  { p_dataset: string; p_add?: string[]; p_remove?: string[] },
  Json
>

/**
 *  The workflows the caller holds on one space, through roles granted to them
 *  or to a group they are in. A Space Administrator has full control over the
 *  space and so incorporates the rest.
 */
export const spaceWorkflows = { apiName: 'space_workflows', kind: 'function' } as FunctionType<
  { p_space: string },
  string[]
>

/**
 *  NULL when the action's criteria hold for these parameters; otherwise the
 *  failure message to show. The form can ask before submitting;
 *  apply_action() asks regardless.
 */
export const submissionCriteriaVerdict = { apiName: 'submission_criteria_verdict', kind: 'function' } as FunctionType<
  { p_action_type: string; p_parameters?: Json },
  string
>

/**
 *  The ten operators submission-criteria names, with the descriptions the
 *  page gives. `arity` is what "operators are pre-filtered to only show a
 *  selection valid for the parameter" means.
 */
export const submissionOperators = { apiName: 'submission_operators', kind: 'function' } as FunctionType<
  Record<string, never>,
  { operator: string; arity: string; note: string }[]
>

/**
 *  Derived, never stored — which is also why "proposals linked to that policy
 *  will be refreshed and have their status reevaluated" costs nothing: the
 *  policy is read at ask time. Rejection dominates. Custom policy on a
 *  protected resource counts eligible non-contributor approvals; the default
 *  policy takes one user with edit permissions; unprotected auto-approves
 *  when the contributor's own permissions covered it.
 */
export const taskApprovalStatus = { apiName: 'task_approval_status', kind: 'function' } as FunctionType<
  { p_task: string },
  string
>

/**
 *  Test policy, as a named user: total rows in the input's current view
 *  versus rows the policy would show them — evaluated through the same
 *  compiled predicate the readers use.
 */
export const testRestrictedView = { apiName: 'test_restricted_view', kind: 'function' } as FunctionType<
  { p_view: string; p_user: string },
  { visible_rows: number; total_rows: number }[]
>

export const titleKeyEligible = { apiName: 'title_key_eligible', kind: 'function' } as FunctionType<
  { p_base_type: string },
  boolean
>

export const typeWidens = { apiName: 'type_widens', kind: 'function' } as FunctionType<
  { p_from: string; p_to: string },
  boolean
>

export const userCanEditResource = { apiName: 'user_can_edit_resource', kind: 'function' } as FunctionType<
  { p_user: string; p_project: string },
  boolean
>

/**
 *  Grammar for user_tools.parameters — every element is {key: lower_snake,
 *  type: text|number|boolean|date, required: bool}.
 */
export const userToolParamsValid = { apiName: 'user_tool_params_valid', kind: 'function' } as FunctionType<
  { p: Json },
  boolean
>

/**
 *  Does a value satisfy the value type's CURRENT constraint — the ontology
 *  never pins a version. NULL conforms (requiredness is the property's
 *  concern). Nested and element recurse through the self-edge, capped at
 *  depth 10 by declared invention.
 */
export const valueConforms = { apiName: 'value_conforms', kind: 'function' } as FunctionType<
  { p_value: Json; p_value_type: string; p_depth?: number },
  boolean
>

/**
 *  Every field both I and someone else have moved since I started. Everything
 *  not listed auto-merges: "Workshop auto-merges changes that do not
 *  overlap." The rows here are what the Update-and-merge dialog asks about.
 */
export const workingStateConflicts = { apiName: 'working_state_conflicts', kind: 'function' } as FunctionType<
  { p_branch?: string },
  { resource_kind: string; resource_id: string; field: string; base_value: Json; mine: Json; theirs: Json }[]
>

