// Regenerate docs/foundry-reference/MAP.md from what is actually mirrored.
//
// CLAUDE.md says of the map: "Grep titles here before concluding Foundry lacks
// something." That instruction is only safe while the map matches the mirror,
// and it was generated by hand — so it drifted to 1,184 pages across 36
// sections while the mirror grew to 2,284 across 82. Half the corpus was
// invisible to the one artifact whose whole job is answering "does a page
// about X exist", which turns a miss into a false "Foundry lacks this".
//
// An index that regenerates itself cannot drift, so mirror-foundry-docs.mjs
// calls this at the end of every run.
//
//   node scripts/build-map.mjs

import fs from 'node:fs'
import path from 'node:path'

const MIRROR = 'docs/foundry-reference/mirror'
const MAP = 'docs/foundry-reference/MAP.md'

/** The page's own H1, which is the title a reader would search for. Falls back
 *  to the slug, because a page with no heading still has to be findable. */
function titleOf(file, slug) {
  const text = fs.readFileSync(file, 'utf8')
  const h1 = text.match(/^#\s+(.+)$/m)
  return h1 === null ? slug : h1[1].trim().replace(/\s+/g, ' ')
}

/** Sections are directories of pages; a nested path (api/v2/…) is one section
 *  named by its whole path, matching how the mirror script is invoked. */
function sections(dir, prefix = '') {
  const out = new Map()
  const pages = []
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (e.name === 'images') continue
      for (const [k, v] of sections(path.join(dir, e.name), prefix ? `${prefix}/${e.name}` : e.name)) {
        out.set(k, v)
      }
    } else if (e.name.endsWith('.md')) {
      const slug = e.name.replace(/\.md$/, '')
      pages.push([slug, titleOf(path.join(dir, e.name), slug)])
    }
  }
  if (pages.length > 0) out.set(prefix, pages.sort((a, b) => a[0].localeCompare(b[0])))
  return out
}

const found = sections(MIRROR)
const names = [...found.keys()].sort()
const total = names.reduce((n, s) => n + found.get(s).length, 0)

const head = `# Map of the mirror

What is in \`docs/foundry-reference/mirror/\`, by section and page title.

**This is a floor plan, not a reading.** It answers "does a page about X exist,
and what is it called" — the question that keeps going wrong. \`staging\` appears
in no URL, but \`manage-models/release-model\` defines it; link semantics are not
in \`search-syntax\` even though the word "link" is. Grep titles here first, then
open the page, then write a reading.

GENERATED — run \`node scripts/build-map.mjs\`, which the mirror script calls
after every run. It was hand-maintained once and drifted to half the corpus,
which made it answer "no such page" for pages that were on disk.

Readings written so far live in \`./readings/\`. One page in a thousand-page
corpus being read is the normal state early on; the map is how the other 999
stay findable.

---


**${total} pages across ${names.length} sections.**
`

const body = names.map((s) => {
  const pages = found.get(s)
  const lines = pages.map(([slug, title]) => `- \`${slug}\` — ${title}`).join('\n')
  return `\n## ${s} — ${pages.length} page${pages.length === 1 ? '' : 's'}\n\n${lines}\n`
}).join('')

fs.writeFileSync(MAP, `${head}${body}`)
console.log(`wrote ${MAP} — ${total} pages across ${names.length} sections`)
