// Generate the typed client from the platform — our Ontology SDK.
//
// "Types and functions are generated from your Ontology, allowing you to query
// and explore your Ontology directly in your editor" (`ontology-sdk/overview`).
// The point is that an entity becomes a VALUE rather than a string:
// `client(Restaurant).fetchOne(…)`, never `.rpc('restaurant')`. A name that does
// not exist stops being a runtime surprise and becomes a compile error, which is
// what deletes `check:rpcs` rather than replacing it.
//
//   pnpm gen:client          write the file
//   pnpm gen:client --check  fail if it is stale (what CI runs)
//
// The --check mode is the point. A generated file nobody regenerates is worse
// than none: it looks authoritative and is quietly wrong.
//
// WHAT IS IN SCOPE, and why it is not a list. Foundry's SDK holds a curated set
// — the Application SDK panel has OBJECT TYPES / ACTION TYPES / FUNCTIONS with
// Add controls and a Save changes button, and "Application access is limited to
// the scopes below, in addition to the user's permissions." That is a security
// scope, not an exemption list. Ours is derived from the same thing the scope
// would express: EXECUTE granted to `authenticated`, which is the role the app
// connects as. Minus two things the catalog also tells us — trigger functions,
// which nothing can call, and anything an extension owns, which is not ours.
//
// OBJECT TYPES are not here yet. The ontology holds none, and generating an
// empty section would be the half-built version CLAUDE.md warns about. When a
// type exists, its section belongs in this file beside the other two.

import fs from 'node:fs'
import path from 'node:path'
import pg from 'pg'
import { connectionString, SSL } from './db-url.mjs'

const OUT = 'packages/platform/src/generated.ts'

// Postgres type to TypeScript. Anything unmapped becomes `unknown` rather than
// `any`, so a new base type shows up as a compile error at the call site.
// Keyed by what `format_type` prints, which is the SQL spelling — not the
// internal `bool`/`int4` names. Getting that wrong types every boolean and
// integer as `unknown`, which compiles at the definition and fails at the use.
const TS = {
  'uuid': 'string', 'text': 'string', 'character varying': 'string', 'name': 'string',
  'boolean': 'boolean',
  'smallint': 'number', 'integer': 'number', 'bigint': 'number', 'numeric': 'number',
  'real': 'number', 'double precision': 'number',
  'json': 'Json', 'jsonb': 'Json',
  'timestamp with time zone': 'string', 'timestamp without time zone': 'string',
  'date': 'string', 'time without time zone': 'string',
  'void': 'void',
}

const tsType = (pgType) => {
  const array = pgType.endsWith('[]')
  const base = array ? pgType.slice(0, -2) : pgType
  const mapped = TS[base] ?? 'unknown'
  return array ? `${mapped}[]` : mapped
}

const camel = (s) => s.split('_').filter(Boolean)
  .map((w, i) => (i === 0 ? w : w[0].toUpperCase() + w.slice(1))).join('')

/** A doc comment from the function's COMMENT, wrapped. */
function docComment(text, indent = '') {
  if (!text) return []
  const words = text.replace(/\s+/g, ' ').trim().split(' ')
  const lines = []
  let line = ''
  for (const w of words) {
    if ((line + ' ' + w).length > 74) { lines.push(line); line = w } else { line = line ? `${line} ${w}` : w }
  }
  if (line) lines.push(line)
  return [`${indent}/**`, ...lines.map((l) => `${indent} *  ${l}`), `${indent} */`]
}

/** `(data_kind = ANY (ARRAY['base_type'::text, 'object'::text]))` → the members.
 *  Only a constraint over ONE column with a literal array is a vocabulary; one
 *  built from a function call has its own source and is skipped above. */
function vocabularies(rows) {
  const out = []
  for (const r of rows) {
    // The left side must be the column itself, not an expression over it.
    const shape = new RegExp(`\\b${r.column} = ANY \\(ARRAY\\[(.*?)\\]\\)`, 's').exec(r.def)
    if (shape === null) continue
    const members = [...shape[1].matchAll(/'((?:[^']|'')*)'::text/g)].map((m) => m[1].replace(/''/g, "'"))
    if (members.length === 0) continue
    out.push({ name: pascal(r.table) + pascal(r.column), table: r.table, column: r.column, members })
  }
  // Two constraints can cover one column — 392 and 638 did exactly that before
  // 789 dropped the duplicate. Keep the first and say nothing twice.
  const seen = new Set()
  return out.filter((v) => (seen.has(v.name) ? false : (seen.add(v.name), true)))
}

const pascal = (s) => s.split('_').filter(Boolean)
  .map((w) => w[0].toUpperCase() + w.slice(1)).join('')

function emit(fns, overloaded, vocab = []) {
  const actions = fns.filter((f) => f.volatility === 'volatile')
  const functions = fns.filter((f) => f.volatility !== 'volatile')

  const lines = [
    '// GENERATED by scripts/generate-client.mjs — do not edit.',
    '//',
    '// Every platform entity the app role may execute, as a typed value. Import',
    '// the entity, not its name: `client(datasetView).executeFunction({…})`.',
    '// Regenerate with `pnpm gen:client`; CI fails if it is stale.',
    '',
    "import type { ActionType, FunctionType, Json } from './client'",
    '',
  ]

  if (vocab.length > 0) {
    lines.push(`// ── Value sets (${String(vocab.length)}) ${'─'.repeat(49)}`)
    lines.push('// Every single-column CHECK whose legal values are a literal array, on a')
    lines.push('// table the app role may read. Hand-writing one of these is how it drifts.')
    lines.push('')
    for (const v of vocab) {
      lines.push(`/** \`${v.table}.${v.column}\` */`)
      lines.push(`export type ${v.name} = ${v.members.map((m) => `'${m}'`).join(' | ')}`)
      lines.push('')
    }
  }

  if (overloaded.length > 0) {
    lines.push('// NOT GENERATED — overloaded, and an entity has one API name:')
    for (const name of overloaded) lines.push(`//   public.${name}`)
    lines.push('')
  }

  const section = (title, note, list, kind) => {
    lines.push(`// ── ${title} (${String(list.length)}) ${'─'.repeat(Math.max(0, 60 - title.length))}`)
    lines.push(`// ${note}`)
    lines.push('')
    for (const f of list) {
      const params = f.args.length === 0
        ? 'Record<string, never>'
        : `{ ${f.args.map((a) => `${a.name}${a.hasDefault ? '?' : ''}: ${tsType(a.type)}`).join('; ')} }`
      const returns = f.columns
        ? `{ ${f.columns.map((c) => `${c.name}: ${tsType(c.type)}`).join('; ')} }[]`
        : f.returnsSet ? `${tsType(f.returnType)}[]` : tsType(f.returnType)

      lines.push(...docComment(f.comment))
      const tag = kind === 'ActionType' ? 'action' : 'function'
      lines.push(`export const ${camel(f.name)} = { apiName: '${f.name}', kind: '${tag}' } as ${kind}<`)
      lines.push(`  ${params},`)
      lines.push(`  ${returns}`)
      lines.push('>')
      lines.push('')
    }
  }

  // "Action types in the Ontology refer to predefined operations that you can
  //  perform on objects within your data model. These actions can create,
  //  modify, and delete objects in the Ontology."
  section('ACTION TYPES', 'Volatile: they may write. Applied, not executed.', actions, 'ActionType')
  // "Functions provide a way to define and execute custom logic on the data
  //  stored in the Ontology… transformations, validations, and analytics."
  section('FUNCTIONS', 'Stable or immutable: they read and return.', functions, 'FunctionType')

  return lines.join('\n') + '\n'
}

const url = connectionString()
if (!url) {
  console.error('SUPABASE_DB_URL not set (environment or .env.local).')
  process.exit(2)
}

const client = new pg.Client({ connectionString: url, ssl: SSL })
await client.connect()
const { rows } = await client.query(`
  SELECT p.proname AS name,
         CASE p.provolatile WHEN 'v' THEN 'volatile' ELSE 'stable' END AS volatility,
         p.proretset AS "returnsSet",
         format_type(p.prorettype, NULL) AS "returnType",
         obj_description(p.oid, 'pg_proc') AS comment,
         -- IN arguments, in order, with which of them carry defaults.
         (SELECT coalesce(jsonb_agg(jsonb_build_object(
                   'name', a.argname,
                   'type', format_type(a.argtype, NULL),
                   'hasDefault', a.ord > p.pronargs - p.pronargdefaults)
                 ORDER BY a.ord), '[]'::jsonb)
            FROM unnest(
                   coalesce(p.proallargtypes::oid[], p.proargtypes::oid[]),
                   coalesce(p.proargnames, array_fill(NULL::text, ARRAY[p.pronargs])),
                   coalesce(p.proargmodes, array_fill('i'::"char", ARRAY[p.pronargs]))
                 ) WITH ORDINALITY AS a(argtype, argname, argmode, ord)
           WHERE a.argmode IN ('i', 'b')) AS args,
         -- A TABLE(...) return arrives as OUT arguments; null when it is scalar.
         (SELECT jsonb_agg(jsonb_build_object(
                   'name', a.argname, 'type', format_type(a.argtype, NULL)) ORDER BY a.ord)
            FROM unnest(p.proallargtypes::oid[], p.proargnames, p.proargmodes)
                 WITH ORDINALITY AS a(argtype, argname, argmode, ord)
           WHERE a.argmode = 't') AS columns
    FROM pg_proc p
   WHERE p.pronamespace = 'public'::regnamespace
     AND p.prokind = 'f'
     -- The scope: what the role the app connects as may execute.
     AND has_function_privilege('authenticated', p.oid, 'EXECUTE')
     -- Nothing can call a trigger function, and an extension's is not ours.
     AND p.prorettype NOT IN ('trigger'::regtype, 'event_trigger'::regtype)
     AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e')
   ORDER BY p.proname`)

// ── the value sets, from the same catalogue and by the same rule ────────────
// A CHECK of the form `col = ANY (ARRAY['a','b'])` IS a vocabulary, and the app
// hand-writes several of them as TypeScript unions. Those drift: `data_kind`
// gained objectSet in 797 and the web learned about it two changes later, when
// an editor needed to offer one. Generating them makes a drift a COMPILE error
// instead of a silent disagreement, which is the same move that deleted
// check:rpcs rather than maintaining it.
//
// Scope is derived, not listed: tables the app role may SELECT. A constraint
// whose legal values come from a FUNCTION rather than a literal array is left
// out — `property_base_types()` is the set, and it already has its own test.
const { rows: valueSets } = await client.query(`
  SELECT c.relname AS "table", a.attname AS "column",
         pg_get_constraintdef(con.oid) AS def
    FROM pg_constraint con
    JOIN pg_class c ON c.oid = con.conrelid
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = con.conkey[1]
   WHERE con.contype = 'c'
     AND con.connamespace = 'public'::regnamespace
     AND c.relkind = 'r'
     AND array_length(con.conkey, 1) = 1
     AND has_table_privilege('authenticated', c.oid, 'SELECT')
     AND pg_get_constraintdef(con.oid) LIKE '%= ANY (ARRAY[%'
   ORDER BY c.relname, a.attname`)

await client.end()

// An entity has ONE API name — "unique across all object types… between 1 and
// 100 characters" — so an overloaded function has no representation here. Left
// out rather than mangled into ridOf3/ridOf4, and named in the file so the gap
// is visible instead of silent.
const byName = new Map()
for (const f of rows) byName.set(f.name, [...(byName.get(f.name) ?? []), f])
const overloaded = [...byName.entries()].filter(([, v]) => v.length > 1).map(([k]) => k)
const entities = rows.filter((f) => !overloaded.includes(f.name))

const next = emit(entities, overloaded, vocabularies(valueSets))
const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''

if (process.argv.includes('--check')) {
  if (current.replace(/\r\n/g, '\n') !== next) {
    console.error(`STALE: ${OUT} does not match the platform. Run \`pnpm gen:client\` and commit.`)
    process.exit(1)
  }
  console.log(`${OUT} is current (${String(entities.length)} entities).`)
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, next)
  console.log(`wrote ${OUT} — ${String(entities.length)} entities, ${String(vocabularies(valueSets).length)} value sets, ${String(overloaded.length)} skipped as overloaded`)
}
