// Self-hosted MapLibre basemap. Serving the whole basemap — tiles, glyphs, and
// sprite — from our OWN domain means no ad-blocker, Brave Shields, CSP, or proxy
// can block it (that was the failure that kept the map black). Tiles are a single
// PMTiles file read via HTTP range requests; the dark style is generated by
// protomaps-themes-base. Both libs are dynamically imported so they only load
// when a basemap is actually configured.
//
// Configure via env, pointing at the Supabase public bucket (migration 195):
//   VITE_BASEMAP_PMTILES_URL  .../storage/v1/object/public/basemap/planet.pmtiles
//   VITE_BASEMAP_GLYPHS_URL   .../basemap/fonts/{fontstack}/{range}.pbf
//   VITE_BASEMAP_SPRITE_URL   .../basemap/sprites/dark
// Unset → the map renders the tile-free SVG pin map (still never black).
// VITE_MAP_STYLE_URL is a separate escape hatch: a full external style URL.

import type { StyleSpecification } from 'maplibre-gl'

const env = import.meta.env as unknown as Record<string, string | undefined>
export const PMTILES_URL = env.VITE_BASEMAP_PMTILES_URL
const GLYPHS   = env.VITE_BASEMAP_GLYPHS_URL
const SPRITE   = env.VITE_BASEMAP_SPRITE_URL
const OVERRIDE = env.VITE_MAP_STYLE_URL

/** True when a real basemap is configured; otherwise the map runs SVG-only. */
export const MAP_TILES = !!PMTILES_URL || !!OVERRIDE

/** Deepest zoom with real data. Our hosted planet extract stops at z8 — zooming
 *  the camera past it overzooms into a near-empty dark canvas that reads as
 *  "map didn't load". Bump VITE_BASEMAP_MAXZOOM when deeper tiles are uploaded.
 *  External override styles are assumed street-level. */
export const BASEMAP_MAX_ZOOM = PMTILES_URL
  ? Number(env.VITE_BASEMAP_MAXZOOM ?? 8)
  : 14

/** The style maplibre should load: our self-hosted Protomaps dark basemap when a
 *  PMTiles URL is set, else an explicit VITE_MAP_STYLE_URL, else null (SVG mode). */
export async function buildMapStyle(): Promise<string | StyleSpecification | null> {
  if (PMTILES_URL) {
    const { layers, namedTheme } = await import('protomaps-themes-base')
    return {
      version: 8,
      glyphs: GLYPHS,
      sprite: SPRITE,
      sources: {
        protomaps: {
          type: 'vector',
          url: `pmtiles://${PMTILES_URL}`,
          attribution: '© <a href="https://openstreetmap.org/copyright">OpenStreetMap</a> · <a href="https://protomaps.com">Protomaps</a>',
        },
      },
      layers: layers('protomaps', namedTheme('dark'), { lang: 'en' }),
    } as StyleSpecification
  }
  return OVERRIDE ?? null
}
