-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 369 — relationship_edges comes back, derived and nothing else.
--
-- 364's CASCADE took the view, because the old builder appended a hand-written
-- branch over `product_variants JOIN products` for sourced_from. That branch is
-- the exact thing DELIVERABLE-MAP named as the standing "never hardcode"
-- violation, and migration 260's claim that the view was "a projection over
-- link_types" was not true while it existed.
--
-- Rebuilt as the claim: every row comes from a backing, and the backings come
-- from link_types. With link_types empty the projection is the generic store
-- alone, which is correct — a join-backed link type contributes rows only once
-- somebody registers it.
--
-- rebuild_relationship_edges_view() is NOT restored. It existed to regenerate
-- this view around that hard-coded branch; a function whose job was to
-- reproduce a special case has nothing to do once the special case is gone. The
-- projection is regenerated by a migration when a join-backed link type is
-- created, which is where that decision belongs.
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

CREATE OR REPLACE VIEW public.relationship_edges AS
  SELECT id, edge_type, source_type, source_id, target_type, target_id,
         hotel_id, triggered_by, actor_id, metadata, created_at
    FROM public.relationship_edges_store;

ALTER VIEW public.relationship_edges SET (security_invoker = true);

GRANT SELECT, INSERT ON public.relationship_edges TO authenticated;
GRANT SELECT, INSERT ON public.relationship_edges TO service_role;

DO $$
DECLARE n int;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.views
                  WHERE table_schema='public' AND table_name='relationship_edges') THEN
    RAISE EXCEPTION 'Migration 369: the projection did not come back';
  END IF;

  -- The point of the rebuild: no table outside the ontology is named in it.
  SELECT count(*) INTO n FROM pg_views
   WHERE schemaname='public' AND viewname='relationship_edges'
     AND (definition ILIKE '%product_variants%' OR definition ILIKE '%products%');
  IF n > 0 THEN
    RAISE EXCEPTION 'Migration 369: the hard-coded join came back with it';
  END IF;
END $$;

COMMIT;
