-- 713: a scenario is a sandbox of action-applied edits over the ontology.
--
-- The adversary pass's largest find: scenarios are not a Vertex shell but a
-- documented ONTOLOGY primitive —
--
--   "A scenario is essentially a sandbox to apply edits on top of the data in your Ontology, generated by applying one or more actions."
--   — ontology/overview-ontology-scenario.md
--
-- and functions chain through it:
--
--   "If the function reads from the Ontology, it will read the state of the Ontology on the scenario. If the function makes Ontology edits, it will make those edits on the scenario."
--   — ontology/overview-ontology-scenario.md
--
-- Here the sandbox is a SECOND EDIT LOG. Applying an action under a
-- scenario context redirects its object_edits rows into scenario_edits —
-- apply_action runs unchanged, its writes intercepted by a trigger keyed on
-- a transaction-local flag, so nothing existing learns about scenarios and
-- the base log stays pure. A scenario read overlays scenario_edits on the
-- indexed base, and the merge copies the sandbox into the real log:
--
--   "Applying the scenario commits all those staged edits to the Ontology as a single transaction via the merge action."
--   — ontology/merge-scenario.md
--
-- An Action-in-scenario is (action type, parameter values), from the
-- sentence the reading first skipped:
--
--   "After choosing which Action to add, you must update the parameters of the Action and select **Submit** to save this Action within your scenario."
--   — vertex/scenarios-getting-started.md
--
-- Vertex's CASE STUDY groups scenarios (prose-supported: "There are many
-- ways to save and share your system graph or case study",
-- vertex/save-share; simulation case studies select from a dropdown,
-- vertex/use-time-selection). The 30-day TTL and ten-minute auto-rebase are
-- RECORDED on the table, not swept — nothing here runs on a timer
-- unattended, by the repo's own rule. Model chaining stays out: it is the
-- SUNSET path ("Model chaining in Vertex is in the sunset phase of
-- development and will be deprecated at a future date.",
-- vertex/chained-models) and this is the documented replacement.
--
-- No scenario RID grammar is attested (scenarioRid is a FIELD in 23 api
-- files, never a literal); the kind token below is inference on the
-- ontology service, whose ri.ontology.main.* forms are attested.

-- ── the scenario ────────────────────────────────────────────────────────────

CREATE TABLE public.ontology_scenarios (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rid             text GENERATED ALWAYS AS (public.rid_of('ontology', 'scenario', id)) STORED,
  organization_id uuid NOT NULL DEFAULT public.auth_org_id()
                    REFERENCES public.organizations(id) ON DELETE CASCADE,
  name            text NOT NULL CHECK (length(btrim(name)) > 0),
  description     text NOT NULL DEFAULT '',
  -- Vertex's grouping: a case study holds scenarios
  case_study_id   uuid,
  -- "the scenario is automatically deleted along with all edits applied to that scenario and the backing persisted scenario object."
  -- — ontology/overview-ontology-scenario.md
  -- (after 30 days; recorded — no sweeper runs unattended here)
  expires_at      timestamptz NOT NULL DEFAULT now() + interval '30 days',
  merged_at       timestamptz,
  created_by      uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ontology_scenarios_rid_key ON public.ontology_scenarios (rid);
CREATE INDEX ontology_scenarios_org_idx ON public.ontology_scenarios (organization_id);
CREATE INDEX ontology_scenarios_case_idx ON public.ontology_scenarios (case_study_id);
CREATE INDEX ontology_scenarios_created_by_idx ON public.ontology_scenarios (created_by);
COMMENT ON TABLE public.ontology_scenarios IS
  '"A scenario is essentially a sandbox to apply edits on top of the data in your Ontology, generated by applying one or more actions" (ontology/overview-ontology-scenario). The sandbox is scenario_edits; the TTL is recorded (expires_at) and enforced by no unattended timer; the ten-minute auto-rebase needs no machinery here because reads overlay the LIVE base — rebase is continuous by construction. The RID kind token is INFERENCE: scenarioRid is a field in twenty-three api files and never a printed literal.';

CREATE TABLE public.vertex_case_studies (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL DEFAULT public.auth_org_id()
                    REFERENCES public.organizations(id) ON DELETE CASCADE,
  project_id      uuid NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  graph_id        uuid REFERENCES public.vertex_graphs(id) ON DELETE SET NULL,
  name            text NOT NULL CHECK (length(btrim(name)) > 0),
  created_by      uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX vertex_case_studies_project_idx ON public.vertex_case_studies (project_id);
CREATE INDEX vertex_case_studies_graph_idx ON public.vertex_case_studies (graph_id);
CREATE INDEX vertex_case_studies_org_idx ON public.vertex_case_studies (organization_id);
CREATE INDEX vertex_case_studies_created_by_idx ON public.vertex_case_studies (created_by);
COMMENT ON TABLE public.vertex_case_studies IS
  'Vertex''s grouping over scenarios — "you can rename this at the top of the scenario pane… You may also rename individual scenarios" (vertex/scenarios-getting-started), saved and shared beside the graph ("your system graph or case study", vertex/save-share). The Case Study → Scenario → Action nesting the captures draw, prose-corroborated.';

ALTER TABLE public.ontology_scenarios
  ADD CONSTRAINT ontology_scenarios_case_study_fkey
  FOREIGN KEY (case_study_id) REFERENCES public.vertex_case_studies(id) ON DELETE SET NULL;

-- ── the sandbox log, same shape as the real one ─────────────────────────────

CREATE TABLE public.scenario_edits (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_id    uuid NOT NULL REFERENCES public.ontology_scenarios(id) ON DELETE CASCADE,
  object_type_id uuid NOT NULL REFERENCES public.object_types(id) ON DELETE CASCADE,
  primary_key    text NOT NULL,
  instruction    text NOT NULL CHECK (instruction IN ('create', 'modify', 'delete')),
  properties     jsonb NOT NULL DEFAULT '{}'::jsonb,
  action_type_id uuid REFERENCES public.action_types(id) ON DELETE SET NULL,
  applied_by     uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  applied_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
  seq            bigserial NOT NULL
);
CREATE INDEX scenario_edits_scenario_idx ON public.scenario_edits (scenario_id, seq);
CREATE INDEX scenario_edits_ot_idx ON public.scenario_edits (object_type_id);
CREATE INDEX scenario_edits_action_idx ON public.scenario_edits (action_type_id);
CREATE INDEX scenario_edits_applied_by_idx ON public.scenario_edits (applied_by);
COMMENT ON TABLE public.scenario_edits IS
  'The sandbox: object_edits'' own shape, one log per scenario, filled by the redirect trigger when an action applies under a scenario context. The base log never sees these rows — "apply edits on top of the data in your Ontology" — until the merge copies them in.';

-- the redirect: apply_action writes object_edits; under a scenario context
-- the rows land in the sandbox instead
CREATE FUNCTION public.redirect_edit_to_scenario()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE sc uuid;
BEGIN
  sc := nullif(current_setting('beacon.scenario_id', true), '')::uuid;
  IF sc IS NULL THEN RETURN NEW; END IF;
  INSERT INTO public.scenario_edits
    (scenario_id, object_type_id, primary_key, instruction, properties, action_type_id, applied_by)
  VALUES (sc, NEW.object_type_id, NEW.primary_key, NEW.instruction, NEW.properties,
          NEW.action_type_id, NEW.applied_by_user_id);
  RETURN NULL; -- the base log stays pure
END $$;
CREATE TRIGGER redirect_edit_to_scenario
  BEFORE INSERT ON public.object_edits
  FOR EACH ROW EXECUTE FUNCTION public.redirect_edit_to_scenario();
COMMENT ON FUNCTION public.redirect_edit_to_scenario() IS
  'The one seam scenarios need: with beacon.scenario_id set (transaction-local, by apply_action_in_scenario), an edit row headed for the base log lands in the scenario''s sandbox instead and the base INSERT is swallowed. apply_action itself runs unchanged — "If the function makes Ontology edits, it will make those edits on the scenario" (ontology/overview-ontology-scenario), enforced below the engine rather than inside it. One recorded divergence: action VALIDATION still reads base state, not scenario state.';

-- ── the actions ledger, and applying into the sandbox ───────────────────────

CREATE TABLE public.scenario_actions (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_id    uuid NOT NULL REFERENCES public.ontology_scenarios(id) ON DELETE CASCADE,
  action_type_id uuid NOT NULL REFERENCES public.action_types(id) ON DELETE CASCADE,
  parameters     jsonb NOT NULL DEFAULT '{}'::jsonb,
  position       integer NOT NULL DEFAULT 0,
  applied_by     uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  applied_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (jsonb_typeof(parameters) = 'object')
);
CREATE INDEX scenario_actions_scenario_idx ON public.scenario_actions (scenario_id, position);
CREATE INDEX scenario_actions_type_idx ON public.scenario_actions (action_type_id);
CREATE INDEX scenario_actions_applied_by_idx ON public.scenario_actions (applied_by);
COMMENT ON TABLE public.scenario_actions IS
  'One Action saved within a scenario — (action type, parameter values), from "you must update the parameters of the Action and select Submit to save this Action within your scenario" (vertex/scenarios-getting-started). The scenario is "generated by applying one or more actions"; this is the ledger of which.';

CREATE FUNCTION public.apply_action_in_scenario(p_scenario uuid, p_action_type uuid,
                                                p_parameters jsonb DEFAULT '{}'::jsonb,
                                                p_primary_key text DEFAULT NULL)
RETURNS uuid LANGUAGE plpgsql
SET search_path TO 'public', 'pg_temp' AS $$
DECLARE sa uuid; n integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.ontology_scenarios s
                  WHERE s.id = p_scenario AND s.merged_at IS NULL) THEN
    RAISE EXCEPTION 'Ontology:ScenarioClosed — % is merged or not a scenario you can see', p_scenario;
  END IF;
  SELECT coalesce(max(position) + 1, 0) INTO n
    FROM public.scenario_actions WHERE scenario_id = p_scenario;
  PERFORM set_config('beacon.scenario_id', p_scenario::text, true);
  PERFORM public.apply_action(p_action_type, p_parameters, p_primary_key);
  PERFORM set_config('beacon.scenario_id', '', true);
  INSERT INTO public.scenario_actions (scenario_id, action_type_id, parameters, position)
  VALUES (p_scenario, p_action_type, p_parameters, n) RETURNING id INTO sa;
  RETURN sa;
END $$;
COMMENT ON FUNCTION public.apply_action_in_scenario(uuid, uuid, jsonb, text) IS
  'Applies one action WITH the scenario context set, so the engine''s edits land in the sandbox, and records the (action type, parameters) row the scenario pane lists. A merged scenario refuses more actions. INVOKER — the action engine''s own permissioning runs unchanged.';

-- ── reading the sandbox: base overlaid with scenario edits ──────────────────

CREATE FUNCTION public.scenario_object_state(p_scenario uuid, p_object_type uuid,
                                             p_primary_key text)
RETURNS jsonb LANGUAGE plpgsql STABLE
SET search_path TO 'public', 'pg_temp' AS $$
DECLARE ot record; state jsonb := NULL; e record; phys text;
BEGIN
  SELECT * INTO ot FROM public.object_types WHERE id = p_object_type;
  -- the base: the indexed object table, when the type is indexed
  phys := 'ot_' || replace(p_object_type::text, '-', '');
  IF EXISTS (SELECT 1 FROM information_schema.tables
              WHERE table_schema = 'objects' AND table_name = phys) THEN
    EXECUTE format('SELECT to_jsonb(o) FROM objects.%I o WHERE o.__pk = %L', phys, p_primary_key)
    INTO state;
  END IF;
  -- the overlay, in order — "the state of the Ontology on the scenario"
  FOR e IN SELECT * FROM public.scenario_edits se
            WHERE se.scenario_id = p_scenario
              AND se.object_type_id = p_object_type
              AND se.primary_key = p_primary_key
            ORDER BY se.seq LOOP
    IF e.instruction = 'delete' THEN
      state := NULL;
    ELSIF e.instruction = 'create' THEN
      state := e.properties;
    ELSE
      state := coalesce(state, '{}'::jsonb) || e.properties;
    END IF;
  END LOOP;
  RETURN state;
END $$;
COMMENT ON FUNCTION public.scenario_object_state(uuid, uuid, text) IS
  'One object as the scenario sees it: the live base overlaid with the sandbox''s edits in sequence — "If the function reads from the Ontology, it will read the state of the Ontology on the scenario" (ontology/overview-ontology-scenario). Because the base is read LIVE, the ten-minute auto-rebase needs no machinery: the overlay always sits on current main.';

-- ── the merge ───────────────────────────────────────────────────────────────

CREATE FUNCTION public.merge_scenario(p_scenario uuid)
RETURNS integer LANGUAGE plpgsql
SET search_path TO 'public', 'pg_temp' AS $$
DECLARE n integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.ontology_scenarios s
                  WHERE s.id = p_scenario AND s.merged_at IS NULL) THEN
    RAISE EXCEPTION 'Ontology:ScenarioClosed — % is merged or not a scenario you can see', p_scenario;
  END IF;
  -- the sandbox lands in the real log, in its own order — and merging is
  -- the page's applying of all the scenario's actions to the Ontology, so
  -- the action context 605's guard demands is set for the copy
  PERFORM set_config('beacon.applying_action', 'on', true);
  INSERT INTO public.object_edits
    (object_type_id, primary_key, instruction, properties, action_type_id, applied_by_user_id)
  SELECT se.object_type_id, se.primary_key, se.instruction, se.properties,
         se.action_type_id, se.applied_by
    FROM public.scenario_edits se
   WHERE se.scenario_id = p_scenario
   ORDER BY se.seq;
  GET DIAGNOSTICS n = ROW_COUNT;
  PERFORM set_config('beacon.applying_action', '', true);
  UPDATE public.ontology_scenarios SET merged_at = now() WHERE id = p_scenario;
  RETURN n;
END $$;
COMMENT ON FUNCTION public.merge_scenario(uuid) IS
  '"Applying the scenario commits all those staged edits to the Ontology as a single transaction via the merge action" (ontology/merge-scenario): the sandbox''s edits copy into the base log in sequence, in one transaction, and the scenario closes. Re-indexing the touched types is the same index_object_type step every base edit already takes. INVOKER.';

-- ── RLS ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.ontology_scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vertex_case_studies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scenario_edits     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scenario_actions   ENABLE ROW LEVEL SECURITY;

CREATE POLICY "org members read scenarios" ON public.ontology_scenarios
  FOR SELECT USING (organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id()));
CREATE POLICY "org members author scenarios" ON public.ontology_scenarios
  FOR ALL USING (organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id()))
          WITH CHECK (organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id()));

CREATE POLICY "project members read case studies" ON public.vertex_case_studies
  FOR SELECT USING (
    organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id())
    AND public.project_role(project_id) IS NOT NULL);
CREATE POLICY "project editors author case studies" ON public.vertex_case_studies
  FOR ALL USING (
    organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id())
    AND public.role_rank(public.project_role(project_id)) >= public.role_rank('editor'))
  WITH CHECK (
    organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id())
    AND public.role_rank(public.project_role(project_id)) >= public.role_rank('editor'));

CREATE POLICY "read scenario edits" ON public.scenario_edits
  FOR SELECT USING (EXISTS (SELECT 1 FROM public.ontology_scenarios s
                             WHERE s.id = scenario_id
                               AND s.organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id())));
CREATE POLICY "write scenario edits" ON public.scenario_edits
  FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.ontology_scenarios s
                                  WHERE s.id = scenario_id
                                    AND s.organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id())));

CREATE POLICY "read scenario actions" ON public.scenario_actions
  FOR SELECT USING (EXISTS (SELECT 1 FROM public.ontology_scenarios s
                             WHERE s.id = scenario_id
                               AND s.organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id())));
CREATE POLICY "write scenario actions" ON public.scenario_actions
  FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.ontology_scenarios s
                                  WHERE s.id = scenario_id
                                    AND s.organization_id IS NOT DISTINCT FROM (SELECT public.auth_org_id())));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.ontology_scenarios  TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.vertex_case_studies TO authenticated;
GRANT SELECT, INSERT                 ON public.scenario_edits      TO authenticated;
GRANT SELECT, INSERT                 ON public.scenario_actions    TO authenticated;

-- ── PROVED BY DOING ─────────────────────────────────────────────────────────

DO $$
DECLARE
  org uuid; sp uuid; proj uuid; ont uuid; ot uuid; at uuid; cs uuid; sc uuid;
  n integer; state jsonb; base_edits integer;
  u1 uuid := gen_random_uuid(); before text;
BEGIN
  before := current_setting('request.jwt.claims', true);
  BEGIN
    INSERT INTO public.organizations (name) VALUES ('vx-713') RETURNING id INTO org;
    INSERT INTO public.spaces (name) VALUES ('vx-713') RETURNING id INTO sp;
    INSERT INTO public.space_organizations (space_id, organization_id) VALUES (sp, org);
    INSERT INTO public.ontologies (space_id, api_name, label, require_resources_in_project)
    VALUES (sp, 'vx713', 'VX713', false) RETURNING id INTO ont;
    INSERT INTO auth.users (id, instance_id, aud, role, email)
    VALUES (u1, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'vx713@beacon.test');
    INSERT INTO public.users (id, email, role, organization_id)
    VALUES (u1, 'vx713@beacon.test', 'admin', org);
    PERFORM set_config('request.jwt.claims',
      json_build_object('sub', u1::text,
        'app_metadata', json_build_object('role', 'admin', 'org_id', org))::text, true);
    INSERT INTO public.projects (organization_id, space_id, api_name, name)
    VALUES (org, sp, 'vx_713', 'VX 713') RETURNING id INTO proj;
    INSERT INTO public.project_role_grants (project_id, user_id, role, organization_id)
    VALUES (proj, u1, 'owner', org);
    INSERT INTO public.object_types (ontology_id, api_name, label)
    VALUES (ont, 'Flight713', 'Flight') RETURNING id INTO ot;

    SELECT count(*) INTO base_edits FROM public.object_edits WHERE object_type_id = ot;

    -- 1. A case study groups a scenario.
    INSERT INTO public.vertex_case_studies (project_id, name)
    VALUES (proj, 'Delay response drill') RETURNING id INTO cs;
    INSERT INTO public.ontology_scenarios (name, case_study_id)
    VALUES ('Divert to SKG', cs) RETURNING id INTO sc;

    -- 2. THE REDIRECT: an edit written under the scenario context lands in
    --    the sandbox and never in the base log.
    -- the flags a real apply_action sets: the action context (so 605's
    -- guard passes, as it does inside the engine) plus the scenario context
    PERFORM set_config('beacon.applying_action', 'on', true);
    PERFORM set_config('beacon.scenario_id', sc::text, true);
    INSERT INTO public.object_edits (object_type_id, primary_key, instruction, properties)
    VALUES (ot, 'FL-1', 'create', '{"status": "diverted", "dest": "SKG"}'::jsonb);
    PERFORM set_config('beacon.scenario_id', '', true);
    PERFORM set_config('beacon.applying_action', '', true);
    SELECT count(*) INTO n FROM public.object_edits WHERE object_type_id = ot;
    IF n <> base_edits THEN RAISE EXCEPTION 'a scenario edit leaked into the base log'; END IF;
    SELECT count(*) INTO n FROM public.scenario_edits WHERE scenario_id = sc;
    IF n <> 1 THEN RAISE EXCEPTION 'the sandbox holds % edits, not 1', n; END IF;

    -- 3. The scenario read overlays: create then modify compose; delete
    --    erases; and the same object outside the scenario is untouched.
    PERFORM set_config('beacon.applying_action', 'on', true);
    PERFORM set_config('beacon.scenario_id', sc::text, true);
    INSERT INTO public.object_edits (object_type_id, primary_key, instruction, properties)
    VALUES (ot, 'FL-1', 'modify', '{"gate": "B7"}'::jsonb);
    PERFORM set_config('beacon.scenario_id', '', true);
    PERFORM set_config('beacon.applying_action', '', true);
    SELECT public.scenario_object_state(sc, ot, 'FL-1') INTO state;
    IF state ->> 'dest' <> 'SKG' OR state ->> 'gate' <> 'B7' THEN
      RAISE EXCEPTION 'the overlay did not compose create + modify';
    END IF;
    IF public.scenario_object_state(sc, ot, 'FL-2') IS NOT NULL THEN
      RAISE EXCEPTION 'an untouched object appeared in the scenario';
    END IF;

    -- 4. The merge copies the sandbox into the base log in order and closes
    --    the scenario against further actions.
    SELECT public.merge_scenario(sc) INTO n;
    IF n <> 2 THEN RAISE EXCEPTION 'the merge copied % edits, not 2', n; END IF;
    SELECT count(*) INTO n FROM public.object_edits
     WHERE object_type_id = ot AND primary_key = 'FL-1';
    IF n <> 2 THEN RAISE EXCEPTION 'the base log did not receive the sandbox'; END IF;
    BEGIN
      PERFORM public.merge_scenario(sc);
      RAISE EXCEPTION 'a merged scenario merged twice';
    EXCEPTION WHEN OTHERS THEN
      IF SQLERRM NOT LIKE 'Ontology:ScenarioClosed%' THEN RAISE; END IF;
    END;

    RAISE EXCEPTION 'rollback the probe';
  EXCEPTION WHEN OTHERS THEN
    PERFORM set_config('request.jwt.claims', coalesce(before, ''), true);
    IF SQLERRM <> 'rollback the probe' THEN RAISE; END IF;
    RAISE NOTICE '713 proved, as the caller: a case study groups a scenario; an edit under the scenario context lands in the sandbox and never in the base log; the scenario read composes create then modify while untouched objects stay untouched; and the merge copies the sandbox into the base log in order, closing the scenario against a second merge';
  END;
END $$;
